export const LABEL_MULTI_LANGUAGE_JSON = {
  vi: {
    full_name: "Họ và tên",
    gender: "Giới tính",
    dob: "Năm sinh",
    age: "Tuổi",
    country: "Quốc gia",
    province: "Tỉnh/Thành phố",
    district: "Quận/Huyện",
    ward: "Xã/Phường",
    address: "Số nhà",
    phoneNumber: "Điện thoại",
    email: "Email",
    symptoms: "Triệu chứng",
    progress: "Diễn biến",
    medical_history: "Tiền sử bệnh",
    compare_link: "So sánh",
    old_date: "Có kết quả cũ",
    section_title: "THÔNG TIN HÀNH CHÍNH",
    image_section: "HÌNH ẢNH MINH HỌA",
    doctor: "BÁC SĨ THỰC HIỆN",
    time: "Thời gian hoàn thành",
    digital_signature: "Chữ ký số",
    Medical_test_result: "PHIẾU KẾT QUẢ",
  },
  en: {
    full_name: "Full name",
    gender: "Sex",
    dob: "Year of birth",
    age: "Year old",
    country: "Nation",
    province: "Province/City",
    district: "District",
    ward: "Commune/Ward",
    address: "Number",
    phoneNumber: "Phone",
    email: "Email",
    symptoms: "Symptom",
    progress: "Developments",
    medical_history: "Medical history",
    compare_link: "Compare",
    old_date: "Have old results",
    section_title: "ADMINISTRATIVE INFORMATION",
    image_section: "ILLUSTRATION",
    doctor: "PERFORMING DOCTOR",
    time: "Completion time",
    digital_signature: "Digital signature",
    Medical_test_result: "RESULTS SHEET",
  },
  zh: {
    full_name: "姓名",
    gender: "性别",
    dob: "出生年份",
    age: "岁",
    country: "国家",
    province: "省/市",
    district: "区",
    ward: "公社/选区",
    address: "数字",
    phoneNumber: "电话",
    email: "电子邮件",
    symptoms: "症状",
    progress: "发展",
    medical_history: "病史",
    compare_link: "比较",
    old_date: "有旧结果",
    section_title: "行政信息",
    image_section: "插图",
    doctor: "执行医生",
    time: "完成时间",
    digital_signature: "数字签名",
    Medical_test_result: "结果表",
  },
  "zh-TW": {
    full_name: "姓名",
    gender: "性別",
    dob: "出生年份",
    age: "歲",
    country: "國家",
    province: "省/市",
    district: "區",
    ward: "公社/選區",
    address: "數位",
    phoneNumber: "電話",
    email: "電子郵件",
    symptoms: "症狀",
    progress: "發展",
    medical_history: "病史",
    compare_link: "比較",
    old_date: "有舊結果",
    section_title: "行政資訊",
    image_section: "插圖",
    doctor: "執行醫生",
    time: "完成時間",
    digital_signature: "數位簽名",
    Medical_test_result: "結果表",
  },
  ja: {
    full_name: "フルネーム",
    gender: "セックス",
    dob: "生年",
    age: "歳",
    country: "国家",
    province: "都道府県/市",
    district: "地区",
    ward: "コミューン/区",
    address: "番号",
    phoneNumber: "電話",
    email: "メール",
    symptoms: "症状",
    progress: "開発",
    medical_history: "病歴",
    compare_link: "比較する",
    old_date: "古い結果がある",
    section_title: "管理情報",
    image_section: "図",
    doctor: "医師",
    time: "完了時間",
    digital_signature: "デジタル署名",
    Medical_test_result: "結果シート",
  },
  ko: {
    full_name: "성명",
    gender: "섹스",
    dob: "출생년도",
    age: "년",
    country: "국가",
    province: "도/시",
    district: "구역",
    ward: "공동체/구",
    address: "숫자",
    phoneNumber: "핸드폰",
    email: "이메일",
    symptoms: "징후",
    progress: "개발",
    medical_history: "병력",
    compare_link: "비교하다",
    old_date: "오래된 결과가 있습니다",
    section_title: "행정 정보",
    image_section: "삽화",
    doctor: "수행 의사",
    time: "완료 시간",
    digital_signature: "디지털 서명",
    Medical_test_result: "결과표",
  },
  fr: {
    full_name: "Nom et prénom",
    gender: "Sexe",
    dob: "Année de naissance",
    age: "Ans",
    country: "Nation",
    province: "Province/Ville",
    district: "District",
    ward: "Commune/Quartier",
    address: "Nombre",
    phoneNumber: "Téléphone",
    email: "E-mail",
    symptoms: "Symptôme",
    progress: "Développements",
    medical_history: "Antécédents médicaux",
    compare_link: "Comparer",
    old_date: "J'ai d'anciens résultats",
    section_title: "INFORMATIONS ADMINISTRATIVES",
    image_section: "ILLUSTRATION",
    doctor: "MÉDECIN ARTISTE",
    time: "Temps d'achèvement",
    digital_signature: "Signature numérique",
    Medical_test_result: "FEUILLE DE RÉSULTATS",
  },
  de: {
    full_name: "Vollständiger Name",
    gender: "Sex",
    dob: "Geburtsjahr",
    age: "Jahr alt",
    country: "Nation",
    province: "Provinz/Stadt",
    district: "Bezirk",
    ward: "Gemeinde/Stadtteil",
    address: "Nummer",
    phoneNumber: "Telefon",
    email: "E-Mail",
    symptoms: "Symptom",
    progress: "Entwicklungen",
    medical_history: "Krankengeschichte",
    compare_link: "Vergleichen",
    old_date: "Alte Ergebnisse haben",
    section_title: "Verwaltungsinformationen",
    image_section: "ILLUSTRATION",
    doctor: "PERSONALARZT",
    time: "Fertigstellungszeit",
    digital_signature: "Digitale Signatur",
    Medical_test_result: "ERGEBNISSE",
  },
  es: {
    full_name: "Nombre completo",
    gender: "Sexo",
    dob: "Año de nacimiento",
    age: "Años de edad",
    country: "Nación",
    province: "Provincia/Ciudad",
    district: "Distrito",
    ward: "Comuna/Barrio",
    address: "Número",
    phoneNumber: "Teléfono",
    email: "Correo electrónico",
    symptoms: "Síntoma",
    progress: "Desarrollos",
    medical_history: "historial médico",
    compare_link: "Comparar",
    old_date: "Tengo resultados antiguos",
    section_title: "INFORMACIÓN ADMINISTRATIVA",
    image_section: "ILUSTRACIÓN",
    doctor: "MÉDICO ACTUANDO",
    time: "Tiempo de finalización",
    digital_signature: "Firma digital",
    Medical_test_result: "HOJA DE RESULTADOS",
  },
  it: {
    full_name: "Nome e cognome",
    gender: "Sesso",
    dob: "Anno di nascita",
    age: "Anno vecchio",
    country: "Nazione",
    province: "Provincia/Città",
    district: "Quartiere",
    ward: "Comune/Rione",
    address: "Numero",
    phoneNumber: "Telefono",
    email: "E-mail",
    symptoms: "Sintomo",
    progress: "Sviluppi",
    medical_history: "Storia medica",
    compare_link: "Confrontare",
    old_date: "Ho vecchi risultati",
    section_title: "INFORMAZIONI AMMINISTRATIVE",
    image_section: "ILLUSTRAZIONE",
    doctor: "MEDICO ESECUTIVO",
    time: "Tempo di completamento",
    digital_signature: "Firma digitale",
    Medical_test_result: "SCHEDA DEI RISULTATI",
  },
  pt: {
    full_name: "Nome completo",
    gender: "Sexo",
    dob: "Ano de nascimento",
    age: "Anos",
    country: "Nação",
    province: "Província/Cidade",
    district: "Distrito",
    ward: "Comuna/Ala",
    address: "Número",
    phoneNumber: "Telefone",
    email: "E-mail",
    symptoms: "Sintoma",
    progress: "Desenvolvimentos",
    medical_history: "Histórico médico",
    compare_link: "Comparar",
    old_date: "Possui resultados antigos",
    section_title: "INFORMAÇÕES ADMINISTRATIVAS",
    image_section: "ILUSTRAÇÃO",
    doctor: "MÉDICO EXECUTOR",
    time: "Tempo de conclusão",
    digital_signature: "Assinatura digital",
    Medical_test_result: "FOLHA DE RESULTADOS",
  },
  ru: {
    full_name: "Полное имя",
    gender: "Секс",
    dob: "Год рождения",
    age: "Годовалый",
    country: "Нация",
    province: "Провинция/Город",
    district: "Округ",
    ward: "Коммуна/округ",
    address: "Число",
    phoneNumber: "Телефон",
    email: "Электронная почта",
    symptoms: "Симптом",
    progress: "Разработки",
    medical_history: "История болезни",
    compare_link: "Сравнивать",
    old_date: "Иметь старые результаты",
    section_title: "АДМИНИСТРАТИВНАЯ ИНФОРМАЦИЯ",
    image_section: "ИЛЛЮСТРАЦИЯ",
    doctor: "ИСПОЛНЯЮЩИЙ ДОКТОР",
    time: "Время завершения",
    digital_signature: "Цифровая подпись",
    Medical_test_result: "ЛИСТ РЕЗУЛЬТАТОВ",
  },
  nl: {
    full_name: "Volledige naam",
    gender: "Seks",
    dob: "Geboortejaar",
    age: "jaar oud",
    country: "Natie",
    province: "Provincie/Stad",
    district: "Wijk",
    ward: "Gemeente/afdeling",
    address: "Nummer",
    phoneNumber: "Telefoon",
    email: "E-mail",
    symptoms: "Symptoom",
    progress: "Ontwikkelingen",
    medical_history: "Medische geschiedenis",
    compare_link: "Vergelijken",
    old_date: "Heb oude resultaten",
    section_title: "ADMINISTRATIEVE INFORMATIE",
    image_section: "ILLUSTRATIE",
    doctor: "UITVOERENDE DOKTER",
    time: "Voltooiingstijd",
    digital_signature: "Digitale handtekening",
    Medical_test_result: "RESULTATENBLAD",
  },
  pl: {
    full_name: "Pełne imię i nazwisko",
    gender: "Seks",
    dob: "Rok urodzenia",
    age: "Rok",
    country: "Naród",
    province: "Prowincja/Miasto",
    district: "Dzielnica",
    ward: "Gmina/dzielnica",
    address: "Numer",
    phoneNumber: "Telefon",
    email: "E-mail",
    symptoms: "Objaw",
    progress: "Rozwój",
    medical_history: "Historia medyczna",
    compare_link: "Porównywać",
    old_date: "Mam stare wyniki",
    section_title: "INFORMACJE ADMINISTRACYJNE",
    image_section: "ILUSTRACJA",
    doctor: "WYKONUJĄCY LEKARZ",
    time: "Czas realizacji",
    digital_signature: "Podpis cyfrowy",
    Medical_test_result: "ARKUSZ WYNIKÓW",
  },
  sv: {
    full_name: "Fullständigt namn",
    gender: "Sex",
    dob: "Födelseår",
    age: "År gammal",
    country: "Nation",
    province: "Provins/Stad",
    district: "Distrikt",
    ward: "Kommun/valkrets",
    address: "Antal",
    phoneNumber: "Telefon",
    email: "E-post",
    symptoms: "Symptom",
    progress: "Utvecklingar",
    medical_history: "Medicinsk historia",
    compare_link: "Jämföra",
    old_date: "Har gamla resultat",
    section_title: "ADMINISTRATIV INFORMATION",
    image_section: "ILLUSTRATION",
    doctor: "UTÖVANDE LÄKARE",
    time: "Slutförandetid",
    digital_signature: "Digital signatur",
    Medical_test_result: "RESULTATBLAD",
  },
  no: {
    full_name: "Fullt navn",
    gender: "Kjønn",
    dob: "Fødselsår",
    age: "År gammel",
    country: "Nasjon",
    province: "Provins/by",
    district: "Distrikt",
    ward: "Kommune/menighet",
    address: "Tall",
    phoneNumber: "Telefon",
    email: "E-post",
    symptoms: "Symptom",
    progress: "Utviklingen",
    medical_history: "Medisinsk historie",
    compare_link: "Sammenligne",
    old_date: "Har gamle resultater",
    section_title: "ADMINISTRATIV INFORMASJON",
    image_section: "ILLUSTRASJON",
    doctor: "UTFØRENDE LEGE",
    time: "Fullføringstid",
    digital_signature: "Digital signatur",
    Medical_test_result: "RESULTATARK",
  },
  da: {
    full_name: "Fulde navn",
    gender: "Køn",
    dob: "Fødselsår",
    age: "År gammel",
    country: "Nation",
    province: "Provins/By",
    district: "Distrikt",
    ward: "Kommune/Valgkreds",
    address: "Antal",
    phoneNumber: "Telefon",
    email: "E-mail",
    symptoms: "Symptom",
    progress: "Udviklinger",
    medical_history: "Medicinsk historie",
    compare_link: "Sammenligne",
    old_date: "Har gamle resultater",
    section_title: "ADMINISTRATIVE OPLYSNINGER",
    image_section: "ILLUSTRATION",
    doctor: "UDØVENDE LÆGE",
    time: "Færdiggørelsestidspunkt",
    digital_signature: "Digital signatur",
    Medical_test_result: "RESULTATARK",
  },
  fi: {
    full_name: "Koko nimi",
    gender: "Seksi",
    dob: "Syntymävuosi",
    age: "Vuoden vanha",
    country: "Kansakunta",
    province: "Maakunta/kaupunki",
    district: "Alue",
    ward: "Kunta/Vuosikerta",
    address: "Määrä",
    phoneNumber: "Puhelin",
    email: "Sähköposti",
    symptoms: "Oire",
    progress: "Kehitys",
    medical_history: "Lääketieteellinen historia",
    compare_link: "Vertaa",
    old_date: "Vanhoja tuloksia",
    section_title: "HALLINNOLLISET TIEDOT",
    image_section: "KUVA",
    doctor: "SUORITTAVA LÄÄKÄRI",
    time: "Valmistumisaika",
    digital_signature: "Digitaalinen allekirjoitus",
    Medical_test_result: "TULOSLOMAKE",
  },
  el: {
    full_name: "Ονοματεπώνυμο",
    gender: "Φύλο",
    dob: "Έτος γέννησης",
    age: "Ένα χρόνο",
    country: "Εθνος",
    province: "Επαρχία/Πόλη",
    district: "Περιοχή",
    ward: "Κοινότητα/Περιφέρεια",
    address: "Αριθμός",
    phoneNumber: "Τηλέφωνο",
    email: "E-mail",
    symptoms: "Σύμπτωμα",
    progress: "Εξελίξεις",
    medical_history: "Ιατρικό ιστορικό",
    compare_link: "Συγκρίνω",
    old_date: "Έχω παλιά αποτελέσματα",
    section_title: "ΔΙΟΙΚΗΤΙΚΕΣ ΠΛΗΡΟΦΟΡΙΕΣ",
    image_section: "ΕΙΚΟΝΑ",
    doctor: "ΕΡΓΑΖΟΜΕΝΟΣ ΓΙΑΤΡΟΣ",
    time: "Χρόνος ολοκλήρωσης",
    digital_signature: "Ψηφιακή υπογραφή",
    Medical_test_result: "ΦΥΛΛΟ ΑΠΟΤΕΛΕΣΜΑΤΩΝ",
  },
  cs: {
    full_name: "Celé jméno",
    gender: "Sex",
    dob: "Rok narození",
    age: "Rok starý",
    country: "Národ",
    province: "Provincie/Město",
    district: "Okres",
    ward: "Obec/Okres",
    address: "Číslo",
    phoneNumber: "Telefon",
    email: "E-mail",
    symptoms: "Příznak",
    progress: "Vývoj",
    medical_history: "Lékařská anamnéza",
    compare_link: "Porovnat",
    old_date: "Mám staré výsledky",
    section_title: "ADMINISTRATIVNÍ INFORMACE",
    image_section: "ILUSTRACE",
    doctor: "VYKONÁVAJÍCÍ LÉKAŘ",
    time: "Doba dokončení",
    digital_signature: "Digitální podpis",
    Medical_test_result: "VÝSLEDKOVÁ LISTINA",
  },
  hu: {
    full_name: "Teljes név",
    gender: "Szex",
    dob: "Születési év",
    age: "éves",
    country: "Nemzet",
    province: "Tartomány/Város",
    district: "Kerület",
    ward: "Község/Körzet",
    address: "Szám",
    phoneNumber: "Telefon",
    email: "Email",
    symptoms: "Tünet",
    progress: "Fejlesztések",
    medical_history: "Kórtörténet",
    compare_link: "Összehasonlítás",
    old_date: "Régi eredményeim vannak",
    section_title: "ADMINISZTRATÍV INFORMÁCIÓK",
    image_section: "ÁBRA",
    doctor: "TELJESÍTŐ ORVOS",
    time: "Befejezési idő",
    digital_signature: "Digitális aláírás",
    Medical_test_result: "EREDMÉNYLÁP",
  },
  ro: {
    full_name: "Numele complet",
    gender: "Sex",
    dob: "Anul nașterii",
    age: "De ani",
    country: "Naţiune",
    province: "Provincie/Oraș",
    district: "District",
    ward: "Comună/Sector",
    address: "Număr",
    phoneNumber: "Telefon",
    email: "E-mail",
    symptoms: "Simptom",
    progress: "Dezvoltări",
    medical_history: "Istoric medical",
    compare_link: "Comparaţie",
    old_date: "Am rezultate vechi",
    section_title: "INFORMAȚII ADMINISTRATIVE",
    image_section: "ILUSTRARE",
    doctor: "MEDIC PERFORMANT",
    time: "Timp de finalizare",
    digital_signature: "Semnătură digitală",
    Medical_test_result: "FOAIA DE REZULTATE",
  },
  bg: {
    full_name: "Пълно име",
    gender: "Секс",
    dob: "Година на раждане",
    age: "Година на възраст",
    country: "Нация",
    province: "Провинция/Град",
    district: "Област",
    ward: "Община/Район",
    address: "Номер",
    phoneNumber: "Телефон",
    email: "Имейл",
    symptoms: "Симптом",
    progress: "Развитие",
    medical_history: "Медицинска история",
    compare_link: "Сравни",
    old_date: "Имат стари резултати",
    section_title: "АДМИНИСТРАТИВНА ИНФОРМАЦИЯ",
    image_section: "ИЛЮСТРАЦИЯ",
    doctor: "ИЗПЪЛНИТЕЛЕН ЛЕКАР",
    time: "Време за завършване",
    digital_signature: "Цифров подпис",
    Medical_test_result: "ЛИСТ С РЕЗУЛТАТИ",
  },
  sk: {
    full_name: "Celé meno",
    gender: "Pohlavie",
    dob: "Rok narodenia",
    age: "Rok starý",
    country: "Národ",
    province: "Provincia/Mesto",
    district: "Okres",
    ward: "Obec/Okres",
    address: "Číslo",
    phoneNumber: "Telefón",
    email: "E-mail",
    symptoms: "Príznak",
    progress: "Vývoj",
    medical_history: "Anamnéza",
    compare_link: "Porovnať",
    old_date: "Mám staré výsledky",
    section_title: "ADMINISTRATÍVNE INFORMÁCIE",
    image_section: "ILUSTRÁCIA",
    doctor: "VYKONÁVAJÚCI LEKÁR",
    time: "Čas dokončenia",
    digital_signature: "Digitálny podpis",
    Medical_test_result: "VÝSLEDKOVÝ LIST",
  },
  sl: {
    full_name: "Polno ime",
    gender: "Seks",
    dob: "Leto rojstva",
    age: "Leto star",
    country: "Narod",
    province: "Pokrajina/mesto",
    district: "Okrožje",
    ward: "Občina/okrožje",
    address: "Številka",
    phoneNumber: "Telefon",
    email: "E-pošta",
    symptoms: "Simptom",
    progress: "Razvoj dogodkov",
    medical_history: "Zdravstvena anamneza",
    compare_link: "Primerjaj",
    old_date: "Imam stare rezultate",
    section_title: "ADMINISTRATIVNE INFORMACIJE",
    image_section: "ILUSTRACIJA",
    doctor: "IZVAJALNI ZDRAVNIK",
    time: "Čas dokončanja",
    digital_signature: "Digitalni podpis",
    Medical_test_result: "REZULTATNI LIST",
  },
  hr: {
    full_name: "Puno ime",
    gender: "Seks",
    dob: "Godina rođenja",
    age: "Star godinu dana",
    country: "Narod",
    province: "Pokrajina/Grad",
    district: "Okrug",
    ward: "Općina/Odjel",
    address: "Broj",
    phoneNumber: "Telefon",
    email: "E-pošta",
    symptoms: "Simptom",
    progress: "Razvoj događaja",
    medical_history: "Medicinska povijest",
    compare_link: "Usporedi",
    old_date: "Imam stare rezultate",
    section_title: "ADMINISTRATIVNE INFORMACIJE",
    image_section: "ILUSTRACIJA",
    doctor: "LIJEČNIK IZVEDBE",
    time: "Vrijeme završetka",
    digital_signature: "Digitalni potpis",
    Medical_test_result: "REZULTATI",
  },
  uk: {
    full_name: "Повне ім'я",
    gender: "Секс",
    dob: "Рік народження",
    age: "Річний",
    country: "Нація",
    province: "Область/Місто",
    district: "Район",
    ward: "Комуна/Район",
    address: "Номер",
    phoneNumber: "Телефон",
    email: "Електронна пошта",
    symptoms: "Симптом",
    progress: "Розробки",
    medical_history: "Історія хвороби",
    compare_link: "Порівняти",
    old_date: "Мають старі результати",
    section_title: "АДМІНІСТРАТИВНА ІНФОРМАЦІЯ",
    image_section: "ІЛЮСТРАЦІЯ",
    doctor: "ВИКОНУЮЧИЙ ЛІКАР",
    time: "Час завершення",
    digital_signature: "Цифровий підпис",
    Medical_test_result: "ТАБЛИЦЯ РЕЗУЛЬТАТІВ",
  },
  sr: {
    full_name: "Пуно име",
    gender: "Секс",
    dob: "Година рођења",
    age: "Година стар",
    country: "Нација",
    province: "Покрајина/Град",
    district: "Округ",
    ward: "Комуна/Одељење",
    address: "Број",
    phoneNumber: "Телефон",
    email: "Е-пошта",
    symptoms: "Симптом",
    progress: "Развој догађаја",
    medical_history: "Медицинска историја",
    compare_link: "Упореди",
    old_date: "Имам старе резултате",
    section_title: "АДМИНИСТРАТИВНЕ ИНФОРМАЦИЈЕ",
    image_section: "ИЛУСТРАЦИЈА",
    doctor: "ИЗВОЂАЧКИ ДОКТОР",
    time: "Време завршетка",
    digital_signature: "Дигитални потпис",
    Medical_test_result: "РЕЗУЛТАТИ",
  },
  lt: {
    full_name: "Pilnas vardas",
    gender: "Seksas",
    dob: "Gimimo metai",
    age: "Metų senumo",
    country: "Tauta",
    province: "Provincija / Miestas",
    district: "Rajonas",
    ward: "Komuna/Rajonas",
    address: "Skaičius",
    phoneNumber: "Telefonas",
    email: "El. paštas",
    symptoms: "Simptomas",
    progress: "Pokyčiai",
    medical_history: "Medicininė istorija",
    compare_link: "Palyginti",
    old_date: "Turi senų rezultatų",
    section_title: "ADMINISTRACINĖ INFORMACIJA",
    image_section: "ILIUSTRACIJA",
    doctor: "ATLIEKAMASIS GYDYTOJAS",
    time: "Užbaigimo laikas",
    digital_signature: "Skaitmeninis parašas",
    Medical_test_result: "REZULTATŲ LAPAS",
  },
  lv: {
    full_name: "Pilns vārds",
    gender: "Sekss",
    dob: "Dzimšanas gads",
    age: "Gadu vecs",
    country: "Nācija",
    province: "Province/Pilsēta",
    district: "Rajons",
    ward: "Komūna/Vieta",
    address: "Numurs",
    phoneNumber: "Tālrunis",
    email: "E-pasts",
    symptoms: "Simptoms",
    progress: "Attīstība",
    medical_history: "Medicīniskā vēsture",
    compare_link: "Salīdzināt",
    old_date: "Ir veci rezultāti",
    section_title: "ADMINISTRATĪVĀ INFORMĀCIJA",
    image_section: "ILUSTRĀCIJA",
    doctor: "IZPILDĀJOŠAIS ĀRSTS",
    time: "Pabeigšanas laiks",
    digital_signature: "Digitālais paraksts",
    Medical_test_result: "REZULTĀTU LAPA",
  },
  et: {
    full_name: "Täisnimi",
    gender: "Seks",
    dob: "Sünniaasta",
    age: "Aastane",
    country: "Riik",
    province: "Provints/linn",
    district: "Piirkond",
    ward: "Kommuun/Valdkond",
    address: "Number",
    phoneNumber: "Telefon",
    email: "E-post",
    symptoms: "Sümptom",
    progress: "Arendused",
    medical_history: "Haiguslugu",
    compare_link: "Võrdle",
    old_date: "Vanad tulemused",
    section_title: "ADMINISTRATIIVNE TEAVE",
    image_section: "ILLUSTRATSIOON",
    doctor: "ESINEV ARST",
    time: "Valmimisaeg",
    digital_signature: "Digitaalallkiri",
    Medical_test_result: "TULEMUSTE LEHT",
  },
  "es-419": {
    full_name: "Nombre completo",
    gender: "Sexo",
    dob: "Año de nacimiento",
    age: "Años de edad",
    country: "Nación",
    province: "Provincia/Ciudad",
    district: "Distrito",
    ward: "Comuna/Barrio",
    address: "Número",
    phoneNumber: "Teléfono",
    email: "Correo electrónico",
    symptoms: "Síntoma",
    progress: "Desarrollos",
    medical_history: "historial médico",
    compare_link: "Comparar",
    old_date: "Tengo resultados antiguos",
    section_title: "INFORMACIÓN ADMINISTRATIVA",
    image_section: "ILUSTRACIÓN",
    doctor: "MÉDICO ACTUANDO",
    time: "Tiempo de finalización",
    digital_signature: "Firma digital",
    Medical_test_result: "HOJA DE RESULTADOS",
  },
  "pt-BR": {
    full_name: "Nome completo",
    gender: "Sexo",
    dob: "Ano de nascimento",
    age: "Anos",
    country: "Nação",
    province: "Província/Cidade",
    district: "Distrito",
    ward: "Comuna/Ala",
    address: "Número",
    phoneNumber: "Telefone",
    email: "E-mail",
    symptoms: "Sintoma",
    progress: "Desenvolvimentos",
    medical_history: "Histórico médico",
    compare_link: "Comparar",
    old_date: "Possui resultados antigos",
    section_title: "INFORMAÇÕES ADMINISTRATIVAS",
    image_section: "ILUSTRAÇÃO",
    doctor: "MÉDICO EXECUTOR",
    time: "Tempo de conclusão",
    digital_signature: "Assinatura digital",
    Medical_test_result: "FOLHA DE RESULTADOS",
  },
  ht: {
    full_name: "Non konplè",
    gender: "Sèks",
    dob: "Ane nesans",
    age: "Ane",
    country: "Nasyon",
    province: "Pwovens/Vil",
    district: "Distri",
    ward: "Komin/Pawas",
    address: "Nimewo",
    phoneNumber: "Telefòn",
    email: "Imèl",
    symptoms: "Sentòm",
    progress: "Devlopman yo",
    medical_history: "Istwa medikal",
    compare_link: "Konpare",
    old_date: "Gen rezilta ansyen",
    section_title: "ENFÒMASYON ADMINISTRATIF",
    image_section: "ILUSTRASYON",
    doctor: "DOKTÈ KI AP PÈFÒME",
    time: "Tan pou fini",
    digital_signature: "Siyati dijital",
    Medical_test_result: "FÈY REZILTA",
  },
  ar: {
    full_name: "الاسم الكامل",
    gender: "الجنس",
    dob: "سنة الميلاد",
    age: "سنة",
    country: "أمة",
    province: "المقاطعة/المدينة",
    district: "يصرف",
    ward: "البلدية/المنطقة",
    address: "رقم",
    phoneNumber: "هاتف",
    email: "بريد إلكتروني",
    symptoms: "الأعراض",
    progress: "التطورات",
    medical_history: "التاريخ الطبي",
    compare_link: "يقارن",
    old_date: "هل لديك نتائج قديمة؟",
    section_title: "المعلومات الإدارية",
    image_section: "توضيح",
    doctor: "طبيب الأداء",
    time: "وقت الانتهاء",
    digital_signature: "التوقيع الرقمي",
    Medical_test_result: "ورقة النتائج",
  },
  fa: {
    full_name: "نام کامل",
    gender: "سکس",
    dob: "سال تولد",
    age: "ساله",
    country: "ملت",
    province: "استان/شهر",
    district: "ناحیه",
    ward: "کمون/بخش",
    address: "شماره",
    phoneNumber: "تلفن",
    email: "ایمیل",
    symptoms: "علامت",
    progress: "تحولات",
    medical_history: "سابقه پزشکی",
    compare_link: "مقایسه",
    old_date: "نتایج قدیمی دارند",
    section_title: "اطلاعات اداری",
    image_section: "تصویرسازی",
    doctor: "پزشک مجری",
    time: "زمان تکمیل",
    digital_signature: "امضای دیجیتال",
    Medical_test_result: "برگه نتایج",
  },
  tr: {
    full_name: "Ad Soyad",
    gender: "Seks",
    dob: "Doğum yılı",
    age: "Yaşında",
    country: "Ulus",
    province: "İl/Şehir",
    district: "Semt",
    ward: "Komün/Mahalle",
    address: "Sayı",
    phoneNumber: "Telefon",
    email: "E-posta",
    symptoms: "Belirti",
    progress: "Gelişmeler",
    medical_history: "Tıbbi geçmişi",
    compare_link: "Karşılaştırmak",
    old_date: "Eski sonuçlara sahip olmak",
    section_title: "İDARİ BİLGİLER",
    image_section: "RESİM",
    doctor: "GÖREVLİ DOKTOR",
    time: "Tamamlanma süresi",
    digital_signature: "Dijital imza",
    Medical_test_result: "SONUÇ SAYFASI",
  },
  he: {
    full_name: "שם מלא",
    gender: "מִין",
    dob: "שנת לידה",
    age: "בן שנה",
    country: "אוּמָה",
    province: "מחוז/עיר",
    district: "מָחוֹז",
    ward: "קומונה/רובע",
    address: "מִספָּר",
    phoneNumber: "טֵלֵפוֹן",
    email: "אֶלֶקטרוֹנִי",
    symptoms: "סִימפּטוֹם",
    progress: "התפתחויות",
    medical_history: "היסטוריה רפואית",
    compare_link: "לְהַשְׁווֹת",
    old_date: "יש תוצאות ישנות",
    section_title: "מידע אדמיניסטרטיבי",
    image_section: "אִיוּר",
    doctor: "רופא מבצע",
    time: "זמן השלמה",
    digital_signature: "חתימה דיגיטלית",
    Medical_test_result: "גיליון תוצאות",
  },
  ur: {
    full_name: "پورا نام",
    gender: "سیکس",
    dob: "پیدائش کا سال",
    age: "سالہ",
    country: "قوم",
    province: "صوبہ/شہر",
    district: "ضلع",
    ward: "کمیون/وارڈ",
    address: "نمبر",
    phoneNumber: "فون",
    email: "ای میل",
    symptoms: "علامت",
    progress: "ترقیات",
    medical_history: "طبی تاریخ",
    compare_link: "موازنہ کریں۔",
    old_date: "پرانے نتائج ہیں۔",
    section_title: "انتظامی معلومات",
    image_section: "مثال",
    doctor: "پرفارمنگ ڈاکٹر",
    time: "تکمیل کا وقت",
    digital_signature: "ڈیجیٹل دستخط",
    Medical_test_result: "رزلٹ شیٹ",
  },
  hi: {
    full_name: "पूरा नाम",
    gender: "लिंग",
    dob: "जन्म का साल",
    age: "साल",
    country: "राष्ट्र",
    province: "प्रांत/शहर",
    district: "ज़िला",
    ward: "कम्यून/वार्ड",
    address: "संख्या",
    phoneNumber: "फ़ोन",
    email: "ईमेल",
    symptoms: "लक्षण",
    progress: "घटनाक्रम",
    medical_history: "चिकित्सा का इतिहास",
    compare_link: "तुलना करना",
    old_date: "पुराने परिणाम हैं",
    section_title: "प्रशासनिक जानकारी",
    image_section: "चित्रण",
    doctor: "प्रदर्शनकारी डॉक्टर",
    time: "पूरा होने का समय",
    digital_signature: "अंगुली का हस्ताक्षर",
    Medical_test_result: "परिणाम पत्रक",
  },
  bn: {
    full_name: "পুরো নাম",
    gender: "লিঙ্গ",
    dob: "জন্ম সাল",
    age: "বছর বয়সী",
    country: "জাতি",
    province: "প্রদেশ/শহর",
    district: "জেলা",
    ward: "কমিউন/ওয়ার্ড",
    address: "সংখ্যা",
    phoneNumber: "ফোন",
    email: "ইমেইল",
    symptoms: "লক্ষণ",
    progress: "উন্নয়ন",
    medical_history: "চিকিৎসার ইতিহাস",
    compare_link: "তুলনা করা",
    old_date: "পুরনো ফলাফল আছে",
    section_title: "প্রশাসনিক তথ্য",
    image_section: "চিত্রণ",
    doctor: "কর্মক্ষম ডাক্তার",
    time: "সমাপ্তির সময়",
    digital_signature: "ডিজিটাল স্বাক্ষর",
    Medical_test_result: "ফলাফলের তালিকা",
  },
  ta: {
    full_name: "முழு பெயர்",
    gender: "செக்ஸ்",
    dob: "பிறந்த ஆண்டு",
    age: "வயது",
    country: "தேசம்",
    province: "மாகாணம்/நகரம்",
    district: "மாவட்டம்",
    ward: "கம்யூன்/வார்டு",
    address: "எண்",
    phoneNumber: "தொலைபேசி",
    email: "மின்னஞ்சல்",
    symptoms: "அறிகுறிகள்",
    progress: "முன்னேற்றங்கள்",
    medical_history: "மருத்துவ வரலாறு",
    compare_link: "ஒப்பிடு",
    old_date: "பழைய முடிவுகள் உள்ளன",
    section_title: "நிர்வாக தகவல்",
    image_section: "விளக்கம்",
    doctor: "செயல்திறன் மருத்துவர்",
    time: "நிறைவு நேரம்",
    digital_signature: "டிஜிட்டல் கையொப்பம்",
    Medical_test_result: "முடிவுகள் தாள்",
  },
  te: {
    full_name: "పూర్తి పేరు",
    gender: "సెక్స్",
    dob: "పుట్టిన సంవత్సరం",
    age: "సంవత్సరం వయస్సు",
    country: "దేశం",
    province: "ప్రావిన్స్/నగరం",
    district: "జిల్లా",
    ward: "కమ్యూన్/వార్డ్",
    address: "సంఖ్య",
    phoneNumber: "ఫోన్",
    email: "ఇ-మెయిల్",
    symptoms: "లక్షణాలు",
    progress: "అభివృద్ధి",
    medical_history: "వైద్య చరిత్ర",
    compare_link: "సరిపోల్చండి",
    old_date: "పాత ఫలితాలు ఉన్నాయి",
    section_title: "పరిపాలనా సమాచారం",
    image_section: "దృష్టాంతం",
    doctor: "పెర్ఫార్మింగ్ డాక్టర్",
    time: "పూర్తి సమయం",
    digital_signature: "డిజిటల్ సంతకం",
    Medical_test_result: "ఫలితాల షీట్",
  },
  ml: {
    full_name: "പൂർണ്ണമായ പേര്",
    gender: "സെക്സ്",
    dob: "ജനനത്തീയതി",
    age: "പ്രായം",
    country: "രാഷ്ട്രം",
    province: "പ്രവിശ്യ/നഗരം",
    district: "ജില്ല",
    ward: "കമ്മ്യൂൺ/വാർഡ്",
    address: "നമ്പർ",
    phoneNumber: "ഫോൺ",
    email: "ഇമെയിൽ",
    symptoms: "ലക്ഷണങ്ങൾ",
    progress: "വികസനങ്ങൾ",
    medical_history: "മെഡിക്കൽ ചരിത്രം",
    compare_link: "താരതമ്യം ചെയ്യുക",
    old_date: "പഴയ ഫലങ്ങൾ ഉണ്ട്",
    section_title: "അഡ്മിനിസ്ട്രേറ്റീവ് വിവരങ്ങൾ",
    image_section: "ചിത്രീകരണം",
    doctor: "പെർഫോമിംഗ് ഡോക്ടർ",
    time: "പൂർത്തീകരണ സമയം",
    digital_signature: "ഡിജിറ്റൽ ഒപ്പ്",
    Medical_test_result: "ഫല ഷീറ്റ്",
  },
  pa: {
    full_name: "ਪੂਰਾ ਨਾਂਮ",
    gender: "ਸੈਕਸ",
    dob: "ਜਨਮ ਦਾ ਸਾਲ",
    age: "ਇੱਕ ਸਾਲ ਪੁਰਾਣਾ",
    country: "ਰਾਸ਼ਟਰ",
    province: "ਸੂਬਾ/ਸ਼ਹਿਰ",
    district: "ਜ਼ਿਲ੍ਹਾ",
    ward: "ਕਮਿਊਨ/ਵਾਰਡ",
    address: "ਨੰਬਰ",
    phoneNumber: "ਫ਼ੋਨ",
    email: "ਈਮੇਲ",
    symptoms: "ਲੱਛਣ",
    progress: "ਵਿਕਾਸ",
    medical_history: "ਡਾਕਟਰੀ ਇਤਿਹਾਸ",
    compare_link: "ਤੁਲਨਾ ਕਰੋ",
    old_date: "ਪੁਰਾਣੇ ਨਤੀਜੇ ਹਨ",
    section_title: "ਪ੍ਰਬੰਧਕੀ ਜਾਣਕਾਰੀ",
    image_section: "ਦ੍ਰਿਸ਼ਟਾਂਤ",
    doctor: "ਪ੍ਰਦਰਸ਼ਨਕਾਰੀ ਡਾਕਟਰ",
    time: "ਪੂਰਾ ਹੋਣ ਦਾ ਸਮਾਂ",
    digital_signature: "ਡਿਜੀਟਲ ਦਸਤਖਤ",
    Medical_test_result: "ਨਤੀਜਾ ਸ਼ੀਟ",
  },
  th: {
    full_name: "ชื่อ-นามสกุล",
    gender: "เพศ",
    dob: "ปีเกิด",
    age: "อายุปี",
    country: "ชาติ",
    province: "จังหวัด/เมือง",
    district: "เขต",
    ward: "ตำบล/แขวง",
    address: "ตัวเลข",
    phoneNumber: "โทรศัพท์",
    email: "อีเมล",
    symptoms: "อาการ",
    progress: "การพัฒนา",
    medical_history: "ประวัติการรักษาพยาบาล",
    compare_link: "เปรียบเทียบ",
    old_date: "มีผลลัพธ์เก่า",
    section_title: "ข้อมูลการบริหาร",
    image_section: "ภาพประกอบ",
    doctor: "แพทย์ผู้ทำการแสดง",
    time: "ระยะเวลาดำเนินการ",
    digital_signature: "ลายเซ็นดิจิทัล",
    Medical_test_result: "ใบผลการสอบ",
  },
  id: {
    full_name: "Nama lengkap",
    gender: "Seks",
    dob: "Tahun lahir",
    age: "Berusia tahun",
    country: "Bangsa",
    province: "Provinsi/Kota",
    district: "Daerah",
    ward: "Komune/Ward",
    address: "Nomor",
    phoneNumber: "Telepon",
    email: "E-mail",
    symptoms: "Gejala",
    progress: "Perkembangan",
    medical_history: "Riwayat kesehatan",
    compare_link: "Membandingkan",
    old_date: "Memiliki hasil lama",
    section_title: "INFORMASI ADMINISTRATIF",
    image_section: "ILUSTRASI",
    doctor: "DOKTER YANG MELAKUKAN",
    time: "Waktu penyelesaian",
    digital_signature: "Tanda tangan digital",
    Medical_test_result: "LEMBAR HASIL",
  },
  ms: {
    full_name: "Nama penuh",
    gender: "Seks",
    dob: "Tahun lahir",
    age: "Berumur tahun",
    country: "bangsa",
    province: "Wilayah/Bandar",
    district: "Daerah",
    ward: "Komune/Wad",
    address: "Nombor",
    phoneNumber: "telefon",
    email: "E-mel",
    symptoms: "simptom",
    progress: "Perkembangan",
    medical_history: "Sejarah perubatan",
    compare_link: "Bandingkan",
    old_date: "Mempunyai keputusan lama",
    section_title: "MAKLUMAT PENTADBIRAN",
    image_section: "MISALAN",
    doctor: "DOKTOR PERSEMBAHAN",
    time: "Masa siap",
    digital_signature: "Tandatangan digital",
    Medical_test_result: "LEMBARAN KEPUTUSAN",
  },
  km: {
    full_name: "ឈ្មោះពេញ",
    gender: "ការរួមភេទ",
    dob: "ឆ្នាំកំណើត",
    age: "មានអាយុមួយឆ្នាំ",
    country: "ជាតិ",
    province: "ខេត្ត/ក្រុង",
    district: "ស្រុក",
    ward: "ឃុំ/សង្កាត់",
    address: "លេខ",
    phoneNumber: "ទូរស័ព្ទ",
    email: "អ៊ីមែល",
    symptoms: "រោគសញ្ញា",
    progress: "ការអភិវឌ្ឍន៍",
    medical_history: "ប្រវត្តិវេជ្ជសាស្ត្រ",
    compare_link: "ប្រៀបធៀប",
    old_date: "ទទួលបានលទ្ធផលចាស់",
    section_title: "ព័ត៌មានរដ្ឋបាល",
    image_section: "រូបភាព",
    doctor: "វេជ្ជបណ្ឌិតអនុវត្ត",
    time: "ពេលវេលាបញ្ចប់",
    digital_signature: "ហត្ថលេខាឌីជីថល",
    Medical_test_result: "សន្លឹកលទ្ធផល",
  },
  lo: {
    full_name: "ຊື່ເຕັມ",
    gender: "ເພດ",
    dob: "ປີເກີດ",
    age: "ປີອາຍຸ",
    country: "ຊາດ",
    province: "ແຂວງ/ເມືອງ",
    district: "ເມືອງ",
    ward: "ຊຸມຊົນ/ຫວອດ",
    address: "ເລກ",
    phoneNumber: "ໂທລະສັບ",
    email: "ອີເມວ",
    symptoms: "ອາການ",
    progress: "ການພັດທະນາ",
    medical_history: "ປະຫວັດທາງການແພດ",
    compare_link: "ປຽບທຽບ",
    old_date: "ມີຜົນໄດ້ຮັບເກົ່າ",
    section_title: "ຂໍ້ມູນບໍລິຫານ",
    image_section: "ຮູບແຕ້ມ",
    doctor: "ແພດປະຕິບັດ",
    time: "ເວລາສໍາເລັດ",
    digital_signature: "ລາຍເຊັນດິຈິຕອນ",
    Medical_test_result: "ໃບຜົນລັບ",
  },
  my: {
    full_name: "နာမည်အပြည့်အစုံ",
    gender: "လိင်",
    dob: "မွေးဖွားသည့်နှစ်",
    age: "အသက် ... နှစ်",
    country: "လူမျိုး",
    province: "ပြည်နယ်/မြို့",
    district: "ခရိုင်",
    ward: "ရပ်ကွက်/ရပ်ကွက်",
    address: "နံပါတ်",
    phoneNumber: "ဖုန်း",
    email: "အီးမေးလ်",
    symptoms: "ရောဂါလက္ခဏာ",
    progress: "တိုးတက်မှုများ",
    medical_history: "ဆေးမှတ်တမ်း",
    compare_link: "နှိုင်းယှဉ်ပါ။",
    old_date: "ရလဒ်ဟောင်းများ ရှိသည်။",
    section_title: "စီမံခန့်ခွဲရေးအချက်အလက်",
    image_section: "ပုံဥပမာ",
    doctor: "ဆောင်ရွက်ပေးနေသော ဆရာဝန်",
    time: "ပြီးစီးချိန်",
    digital_signature: "ဒစ်ဂျစ်တယ်လက်မှတ်",
    Medical_test_result: "ရလဒ်စာရွက်",
  },
  fil: {
    full_name: "Buong pangalan",
    gender: "kasarian",
    dob: "Taon ng kapanganakan",
    age: "Taon gulang",
    country: "Nasyon",
    province: "Lalawigan/Lungsod",
    district: "Distrito",
    ward: "Commune/Ward",
    address: "Numero",
    phoneNumber: "Telepono",
    email: "Email",
    symptoms: "Sintomas",
    progress: "Mga Pag-unlad",
    medical_history: "Kasaysayan ng medikal",
    compare_link: "Ikumpara",
    old_date: "Magkaroon ng mga lumang resulta",
    section_title: "IMPORMASYON NA PANGANGASIWA",
    image_section: "ILUSTRASYON",
    doctor: "NAGMAMAYANG DOKTOR",
    time: "Oras ng pagkumpleto",
    digital_signature: "Digital na lagda",
    Medical_test_result: "SHEET NG RESULTA",
  },
  sw: {
    full_name: "Jina kamili",
    gender: "Ngono",
    dob: "Mwaka wa kuzaliwa",
    age: "Umri wa miaka",
    country: "Taifa",
    province: "Mkoa/Jiji",
    district: "Wilaya",
    ward: "Wilaya/Wadi",
    address: "Nambari",
    phoneNumber: "Simu",
    email: "Barua pepe",
    symptoms: "Dalili",
    progress: "Maendeleo",
    medical_history: "Historia ya matibabu",
    compare_link: "Linganisha",
    old_date: "Kuwa na matokeo ya zamani",
    section_title: "TAARIFA ZA UTAWALA",
    image_section: "MFANO",
    doctor: "DAKTARI WA UTENDAJI",
    time: "Muda wa kukamilika",
    digital_signature: "Sahihi ya dijiti",
    Medical_test_result: "KARATASI YA MATOKEO",
  },
  am: {
    full_name: "ሙሉ ስም",
    gender: "ወሲብ",
    dob: "የትውልድ ዓመት",
    age: "አመት",
    country: "ብሄር",
    province: "አውራጃ/ከተማ",
    district: "ወረዳ",
    ward: "ኮምዩን/ዋርድ",
    address: "ቁጥር",
    phoneNumber: "ስልክ",
    email: "ኢሜይል",
    symptoms: "ምልክት",
    progress: "እድገቶች",
    medical_history: "የሕክምና ታሪክ",
    compare_link: "አወዳድር",
    old_date: "የቆዩ ውጤቶች ይኑርዎት",
    section_title: "የአስተዳደር መረጃ",
    image_section: "ILUSTRATION",
    doctor: "በማከናወን ላይ ሐኪም",
    time: "የማጠናቀቂያ ጊዜ",
    digital_signature: "ዲጂታል ፊርማ",
    Medical_test_result: "የውጤት ሉህ",
  },
  af: {
    full_name: "Volle naam",
    gender: "Seks",
    dob: "Geboortejaar",
    age: "Jaar oud",
    country: "Nasie",
    province: "Provinsie/Stad",
    district: "Distrik",
    ward: "Kommune/Wyk",
    address: "Nommer",
    phoneNumber: "Foon",
    email: "E-pos",
    symptoms: "Simptoom",
    progress: "Ontwikkelings",
    medical_history: "Mediese geskiedenis",
    compare_link: "Vergelyk",
    old_date: "Het ou resultate",
    section_title: "ADMINISTRATIEWE INLIGTING",
    image_section: "ILLUSTRASIE",
    doctor: "UITVOERENDE DOKTER",
    time: "Voltooiingstyd",
    digital_signature: "Digitale handtekening",
    Medical_test_result: "RESULTATEBLAD",
  },
  yo: {
    full_name: "Akokun Oruko",
    gender: "Ibalopo",
    dob: "Ọdun ibi",
    age: "Odun kan",
    country: "Orilẹ-ede",
    province: "Agbegbe / Ilu",
    district: "Agbegbe",
    ward: "Agbegbe / Ward",
    address: "Nọmba",
    phoneNumber: "Foonu",
    email: "Imeeli",
    symptoms: "Aisan",
    progress: "Awọn idagbasoke",
    medical_history: "Itan iṣoogun",
    compare_link: "Afiwera",
    old_date: "Ni awọn abajade atijọ",
    section_title: "ALAYE Isakoso",
    image_section: "Àpèjúwe",
    doctor: "ONISEGUN",
    time: "Akoko ipari",
    digital_signature: "Ibuwọlu oni-nọmba",
    Medical_test_result: "IWE esi",
  },
  ig: {
    full_name: "Aha n'uju",
    gender: "Mmekọahụ",
    dob: "Afọ ọmụmụ",
    age: "Otu afọ",
    country: "Mba",
    province: "Mpaghara/Obodo",
    district: "Mpaghara",
    ward: "Ụlọ ọrụ / Ward",
    address: "Nọmba",
    phoneNumber: "Ekwentị",
    email: "Email",
    symptoms: "Mgbaàmà",
    progress: "Mmepe",
    medical_history: "Akụkọ gbasara ahụike",
    compare_link: "Tulee",
    old_date: "Nwee nsonaazụ ochie",
    section_title: "Ozi nchịkwa",
    image_section: "Ntụle",
    doctor: "Dọkịta na-eme",
    time: "Oge mmecha",
    digital_signature: "mbinye aka dijitalụ",
    Medical_test_result: "Mpempe akwụkwọ nsonaazụ",
  },
  ha: {
    full_name: "Cikakken suna",
    gender: "Jima'i",
    dob: "Shekarar haihuwa",
    age: "Shekara daya",
    country: "Kasa",
    province: "Lardi / Birni",
    district: "Gundumar",
    ward: "Sadarwa/Ward",
    address: "Lamba",
    phoneNumber: "Waya",
    email: "Imel",
    symptoms: "Alama",
    progress: "Ci gaba",
    medical_history: "Tarihin likita",
    compare_link: "Kwatanta",
    old_date: "Yi tsohon sakamako",
    section_title: "BAYANIN MULKI",
    image_section: "MISALI",
    doctor: "LIKITA MAI YI",
    time: "Lokacin kammalawa",
    digital_signature: "Sa hannu na dijital",
    Medical_test_result: "BAYANIN SAKAMAKO",
  },
  is: {
    full_name: "Fullt nafn",
    gender: "Kynlíf",
    dob: "Fæðingarár",
    age: "Árs gamalt",
    country: "Þjóð",
    province: "Sýsla/borg",
    district: "Hérað",
    ward: "Sveitarfélag/Kjördæmi",
    address: "Fjöldi",
    phoneNumber: "Sími",
    email: "Tölvupóstur",
    symptoms: "Einkenni",
    progress: "Þróun",
    medical_history: "Sjúkrasaga",
    compare_link: "Bera saman",
    old_date: "Hef gamlar niðurstöður",
    section_title: "STJÓRNVÖRUUPPLÝSINGAR",
    image_section: "MYNDSKEIÐ",
    doctor: "LÆKNIR Í STARFSEMI",
    time: "Lokatími",
    digital_signature: "Stafræn undirskrift",
    Medical_test_result: "NIÐURSTÖÐUBLÖÐ",
  },
  ga: {
    full_name: "Ainm iomlán",
    gender: "Gnéas",
    dob: "Bliain bhreithe",
    age: "Bliain d'aois",
    country: "Náisiún",
    province: "Cúige/Cathair",
    district: "Ceantar",
    ward: "Común/Barda",
    address: "Uimhir",
    phoneNumber: "Fón",
    email: "Ríomhphost",
    symptoms: "Siomptóim",
    progress: "Forbairtí",
    medical_history: "Stair leighis",
    compare_link: "Déan comparáid",
    old_date: "Tá seanthorthaí agam",
    section_title: "FAISNÉIS RIARACHÁIN",
    image_section: "LÉARÚ",
    doctor: "DOCHTÚIR FEIRMIÚCHÁIN",
    time: "Am críochnaithe",
    digital_signature: "Síniú digiteach",
    Medical_test_result: "BILEOG TORTHAÍ",
  },
  mt: {
    full_name: "Isem sħiħ",
    gender: "Sess",
    dob: "Sena tat-twelid",
    age: "Sena",
    country: "Nazzjon",
    province: "Provinċja/Belt",
    district: "Distrett",
    ward: "Komun/Ward",
    address: "Numru",
    phoneNumber: "Telefon",
    email: "Email",
    symptoms: "Sintomu",
    progress: "Żviluppi",
    medical_history: "Storja medika",
    compare_link: "Qabbel",
    old_date: "Għandi riżultati qodma",
    section_title: "INFORMAZZJONI AMMINISTRATTIVA",
    image_section: "ILLUSTRAZZJONI",
    doctor: "TABIB LI JIPPERFORMA",
    time: "Ħin tat-tlestija",
    digital_signature: "Firma diġitali",
    Medical_test_result: "SKEDA TAR-RIŻULTATI",
  },
  cy: {
    full_name: "Enw llawn",
    gender: "Rhyw",
    dob: "Blwyddyn geni",
    age: "Blwyddyn oed",
    country: "Cenedl",
    province: "Talaith/Dinas",
    district: "Ardal",
    ward: "Cymuned/Ward",
    address: "Rhif",
    phoneNumber: "Ffôn",
    email: "E-bost",
    symptoms: "Symptom",
    progress: "Datblygiadau",
    medical_history: "Hanes meddygol",
    compare_link: "Cymharwch",
    old_date: "Mae ganddo ganlyniadau hen",
    section_title: "GWYBODAETH WEINYDDOL",
    image_section: "DARLUNIAD",
    doctor: "MEDDYG PERFFORMIO",
    time: "Amser cwblhau",
    digital_signature: "Llofnod digidol",
    Medical_test_result: "TAFLEN CANLYNIADAU",
  },
};
