export const TRANSLATE_MULTI_REPORT = {
  vi: {
    administrativeInfo: "THÔNG TIN HÀNH CHÍNH",
    fullName: "Họ tên",
    gender: "Giới tính",
    age: "Tuổi",
    nationality: "Quốc tịch",
    phone: "Điện thoại",
    email: "Email",
    patientId: "Mã số bệnh nhân PID",
    sid: "Mã số phiếu SID",
    province: "Tỉnh/Thành phố",
    district: "Phường/Xã",
    address: "Địa chỉ",
    clinical: "Lâm sàng",
    department: "Phân hệ",
    division: "Chuyên khoa",
    codeForm: "Mã số định danh mẫu",
    bodyPart: "Bộ phận",
    resultTemplate: "Mẫu đọc kết quả",
    resultPrint: "Mẫu in kết quả",
    language: "Ngôn ngữ",
    formName: "Tên mẫu",
    formResult: "Kết luận của mẫu",
    createdAt: "Ngày thực hiện",
    createdUser: "Người thực hiện",

    technicalProtocol: "QUY TRÌNH KỸ THUẬT",
    imagingFindings: "MÔ TẢ HÌNH ẢNH",
    impression: "KẾT LUẬN, CHẨN ĐOÁN",
    icd10Classification: "Phân loại ICD-10",
    gradingClassification: "Phân độ, phân loại",
    differentialDiagnosis: "Chẩn đoán phân biệt",
    recommendationsCounseling: "KHUYẾN NGHỊ & TƯ VẤN",
    illustrativeImages: "HÌNH ẢNH MINH HỌA",
    doctor: "BÁC SỸ THỰC HIỆN",
    time: "Thời gian",
    Result_Report: "Phiếu kết quả",
    "Tiêm thuốc đối quang": "Tiêm thuốc đối quang",
    "Chất lượng hình ảnh": "Chất lượng hình ảnh",
    "Thực hiện bổ sung": "Thực hiện bổ sung",
    "Mô tả chi tiết": "Mô tả chi tiết",
    "Chẩn đoán hình ảnh": "Chẩn đoán hình ảnh",
    "Kỹ thuật thực hiện": "Kỹ thuật thực hiện",
    "QUY TRÌNH KỸ THUẬT": "QUY TRÌNH KỸ THUẬT",
    "Chỉ định": "Chỉ định",
    Conslusion: "Kết luận",
  },
  en: {
    administrativeInfo: "ADMINISTRATIVE INFORMATION",
    fullName: "Full name",
    gender: "Sex",
    age: "Year old",
    nationality: "Nationality",
    phone: "Phone",
    email: "Email",
    patientId: "PID patient number",
    sid: "SID Code",
    province: "Province/City",
    district: "Ward/Commune",
    address: "Address",
    clinical: "Clinical",
    department: "Subsystem",
    division: "Specialty",
    codeForm: "Sample identification number",
    bodyPart: "Part",
    resultTemplate: "Sample reading of results",
    resultPrint: "Print results form",
    language: "Language",
    formName: "Model name",
    formResult: "Conclusion of the sample",
    createdAt: "Date of implementation",
    createdUser: "The performer",
    technicalProtocol: "TECHNICAL PROCESS",
    imagingFindings: "IMAGE DESCRIPTION",
    impression: "CONCLUSION, DIAGNOSIS",
    icd10Classification: "ICD-10 Classification",
    gradingClassification: "Grading, classification",
    differentialDiagnosis: "Differential diagnosis",
    recommendationsCounseling: "RECOMMENDATIONS & ADVICE",
    illustrativeImages: "ILLUSTRATION",
    doctor: "PERFORMING DOCTOR",
    time: "Time",
    Result_Report: "Result sheet",
    "Tiêm thuốc đối quang": "Contrast injection",
    "Chất lượng hình ảnh": "Image quality",
    "Thực hiện bổ sung": "Additional procedure",
    "Mô tả chi tiết": "Detailed description",
    "Chẩn đoán hình ảnh": "Imaging diagnosis",
    "Kỹ thuật thực hiện": "Technical procedure",
    "QUY TRÌNH KỸ THUẬT": "Technical procedure",
    "Chỉ định": "Indication",
    Conslusion: "Conslusion",
  },
  zh: {
    administrativeInfo: "行政信息",
    fullName: "姓名",
    gender: "性别",
    age: "岁",
    nationality: "国籍",
    phone: "电话",
    email: "电子邮件",
    patientId: "PID 患者编号",
    sid: "SID码",
    province: "省/市",
    district: "病房/公社",
    address: "地址",
    clinical: "临床",
    department: "子系统",
    division: "专业",
    codeForm: "样品识别号",
    bodyPart: "部分",
    resultTemplate: "结果样本读取",
    resultPrint: "打印结果表",
    language: "语言",
    formName: "型号名称",
    formResult: "样本结论",
    createdAt: "实施日期",
    createdUser: "表演者",
    technicalProtocol: "技术流程",
    imagingFindings: "图片描述",
    impression: "结论、诊断",
    icd10Classification: "ICD-10 分类",
    gradingClassification: "分级、分类",
    differentialDiagnosis: "鉴别诊断",
    recommendationsCounseling: "建议与意见",
    illustrativeImages: "插图",
    doctor: "执行医生",
    time: "时间",
    Result_Report: "结果表",
  },
  "zh-TW": {
    administrativeInfo: "行政資訊",
    fullName: "姓名",
    gender: "性別",
    age: "歲",
    nationality: "國籍",
    phone: "電話",
    email: "電子郵件",
    patientId: "PID 患者編號",
    sid: "SID碼",
    province: "省/市",
    district: "病房/公社",
    address: "地址",
    clinical: "臨床",
    department: "子系統",
    division: "專業",
    codeForm: "樣品識別號",
    bodyPart: "部分",
    resultTemplate: "結果樣本讀取",
    resultPrint: "列印結果表",
    language: "語言",
    formName: "型號名稱",
    formResult: "樣本結論",
    createdAt: "實施日期",
    createdUser: "表演者",
    technicalProtocol: "技術流程",
    imagingFindings: "圖片描述",
    impression: "結論、診斷",
    icd10Classification: "ICD-10 分類",
    gradingClassification: "分級、分類",
    differentialDiagnosis: "鑑別診斷",
    recommendationsCounseling: "建議與意見",
    illustrativeImages: "插圖",
    doctor: "執行醫生",
    time: "時間",
    Result_Report: "結果表",
  },
  ja: {
    administrativeInfo: "管理情報",
    fullName: "フルネーム",
    gender: "セックス",
    age: "歳",
    nationality: "国籍",
    phone: "電話",
    email: "メール",
    patientId: "PID患者番号",
    sid: "SIDコード",
    province: "都道府県/市",
    district: "区/コミューン",
    address: "住所",
    clinical: "臨床",
    department: "サブシステム",
    division: "専門",
    codeForm: "サンプル識別番号",
    bodyPart: "一部",
    resultTemplate: "結果のサンプル読み取り",
    resultPrint: "結果フォームを印刷する",
    language: "言語",
    formName: "モデル名",
    formResult: "サンプルの結論",
    createdAt: "実施日",
    createdUser: "演者",
    technicalProtocol: "技術的プロセス",
    imagingFindings: "画像の説明",
    impression: "結論、診断",
    icd10Classification: "ICD-10分類",
    gradingClassification: "グレーディング、分類",
    differentialDiagnosis: "鑑別診断",
    recommendationsCounseling: "推奨事項とアドバイス",
    illustrativeImages: "図",
    doctor: "医師",
    time: "時間",
    Result_Report: "結果シート",
  },
  ko: {
    administrativeInfo: "행정 정보",
    fullName: "성명",
    gender: "섹스",
    age: "년",
    nationality: "국적",
    phone: "핸드폰",
    email: "이메일",
    patientId: "PID 환자 번호",
    sid: "SID 코드",
    province: "도/시",
    district: "와드/코뮌",
    address: "주소",
    clinical: "객관적인",
    department: "하위 시스템",
    division: "전문",
    codeForm: "샘플 식별 번호",
    bodyPart: "부분",
    resultTemplate: "결과의 샘플 판독",
    resultPrint: "결과 인쇄 양식",
    language: "언어",
    formName: "모델명",
    formResult: "샘플의 결론",
    createdAt: "시행일자",
    createdUser: "공연자",
    technicalProtocol: "기술 프로세스",
    imagingFindings: "이미지 설명",
    impression: "결론, 진단",
    icd10Classification: "ICD-10 분류",
    gradingClassification: "등급, 분류",
    differentialDiagnosis: "감별진단",
    recommendationsCounseling: "추천 및 조언",
    illustrativeImages: "삽화",
    doctor: "수행 의사",
    time: "시간",
    Result_Report: "결과지",
  },
  fr: {
    administrativeInfo: "INFORMATIONS ADMINISTRATIVES",
    fullName: "Nom et prénom",
    gender: "Sexe",
    age: "Ans",
    nationality: "Nationalité",
    phone: "Téléphone",
    email: "E-mail",
    patientId: "numéro de patient PID",
    sid: "Code SID",
    province: "Province/Ville",
    district: "Quartier/Commune",
    address: "Adresse",
    clinical: "Clinique",
    department: "Sous-système",
    division: "Spécialité",
    codeForm: "Numéro d'identification de l'échantillon",
    bodyPart: "Partie",
    resultTemplate: "Exemple de lecture des résultats",
    resultPrint: "Formulaire d'impression des résultats",
    language: "Langue",
    formName: "Nom du modèle",
    formResult: "Conclusion de l'échantillon",
    createdAt: "Date de mise en œuvre",
    createdUser: "L'artiste",
    technicalProtocol: "PROCESSUS TECHNIQUE",
    imagingFindings: "DESCRIPTION DE L'IMAGE",
    impression: "CONCLUSION, DIAGNOSTIC",
    icd10Classification: "Classification CIM-10",
    gradingClassification: "Évaluation, classification",
    differentialDiagnosis: "Diagnostic différentiel",
    recommendationsCounseling: "RECOMMANDATIONS ET CONSEILS",
    illustrativeImages: "ILLUSTRATION",
    doctor: "MÉDECIN ARTISTE",
    time: "Temps",
    Result_Report: "Feuille de résultats",
  },
  de: {
    administrativeInfo: "Verwaltungsinformationen",
    fullName: "Vollständiger Name",
    gender: "Sex",
    age: "Jahr alt",
    nationality: "Nationalität",
    phone: "Telefon",
    email: "E-Mail",
    patientId: "PID-Patientennummer",
    sid: "SID-Code",
    province: "Provinz/Stadt",
    district: "Bezirk/Gemeinde",
    address: "Adresse",
    clinical: "Klinisch",
    department: "Teilsystem",
    division: "Spezialität",
    codeForm: "Probenidentifikationsnummer",
    bodyPart: "Teil",
    resultTemplate: "Beispielhafte Ablesung der Ergebnisse",
    resultPrint: "Ergebnisse drucken",
    language: "Sprache",
    formName: "Modellname",
    formResult: "Schlussfolgerung der Stichprobe",
    createdAt: "Datum der Umsetzung",
    createdUser: "Der Künstler",
    technicalProtocol: "TECHNISCHER PROZESS",
    imagingFindings: "BILDBESCHREIBUNG",
    impression: "SCHLUSSFOLGERUNG, DIAGNOSE",
    icd10Classification: "ICD-10-Klassifikation",
    gradingClassification: "Bewertung, Klassifizierung",
    differentialDiagnosis: "Differenzialdiagnose",
    recommendationsCounseling: "EMPFEHLUNGEN & RATSCHLÄGE",
    illustrativeImages: "ILLUSTRATION",
    doctor: "PERSONALARZT",
    time: "Zeit",
    Result_Report: "Ergebnisliste",
  },
  es: {
    administrativeInfo: "INFORMACIÓN ADMINISTRATIVA",
    fullName: "Nombre completo",
    gender: "Sexo",
    age: "Años de edad",
    nationality: "Nacionalidad",
    phone: "Teléfono",
    email: "Correo electrónico",
    patientId: "número de paciente con EPI",
    sid: "Código SID",
    province: "Provincia/Ciudad",
    district: "Barrio/Comuna",
    address: "DIRECCIÓN",
    clinical: "Clínico",
    department: "Subsistema",
    division: "Especialidad",
    codeForm: "Número de identificación de la muestra",
    bodyPart: "Parte",
    resultTemplate: "Ejemplo de lectura de resultados",
    resultPrint: "Formulario de resultados de impresión",
    language: "Idioma",
    formName: "Nombre del modelo",
    formResult: "Conclusión de la muestra",
    createdAt: "Fecha de implementación",
    createdUser: "El intérprete",
    technicalProtocol: "PROCESO TÉCNICO",
    imagingFindings: "DESCRIPCIÓN DE LA IMAGEN",
    impression: "CONCLUSIÓN, DIAGNÓSTICO",
    icd10Classification: "Clasificación CIE-10",
    gradingClassification: "Calificación, clasificación",
    differentialDiagnosis: "Diagnóstico diferencial",
    recommendationsCounseling: "RECOMENDACIONES Y CONSEJOS",
    illustrativeImages: "ILUSTRACIÓN",
    doctor: "MÉDICO ACTUANDO",
    time: "Tiempo",
    Result_Report: "Hoja de resultados",
  },
  it: {
    administrativeInfo: "INFORMAZIONI AMMINISTRATIVE",
    fullName: "Nome e cognome",
    gender: "Sesso",
    age: "Anno vecchio",
    nationality: "Nazionalità",
    phone: "Telefono",
    email: "E-mail",
    patientId: "Numero del paziente PID",
    sid: "codice SID",
    province: "Provincia/Città",
    district: "Rione/Comune",
    address: "Indirizzo",
    clinical: "Clinico",
    department: "Sottosistema",
    division: "Specialità",
    codeForm: "Numero di identificazione del campione",
    bodyPart: "Parte",
    resultTemplate: "Esempio di lettura dei risultati",
    resultPrint: "Stampa il modulo dei risultati",
    language: "Lingua",
    formName: "Nome del modello",
    formResult: "Conclusione del campione",
    createdAt: "Data di implementazione",
    createdUser: "L'esecutore",
    technicalProtocol: "PROCESSO TECNICO",
    imagingFindings: "DESCRIZIONE DELL'IMMAGINE",
    impression: "CONCLUSIONE, DIAGNOSI",
    icd10Classification: "Classificazione ICD-10",
    gradingClassification: "Classificazione, classificazione",
    differentialDiagnosis: "Diagnosi differenziale",
    recommendationsCounseling: "RACCOMANDAZIONI E CONSIGLI",
    illustrativeImages: "ILLUSTRAZIONE",
    doctor: "MEDICO ESECUTIVO",
    time: "Tempo",
    Result_Report: "Foglio dei risultati",
  },
  pt: {
    administrativeInfo: "INFORMAÇÕES ADMINISTRATIVAS",
    fullName: "Nome completo",
    gender: "Sexo",
    age: "Anos",
    nationality: "Nacionalidade",
    phone: "Telefone",
    email: "E-mail",
    patientId: "número do paciente PID",
    sid: "Código SID",
    province: "Província/Cidade",
    district: "Bairro/Comuna",
    address: "Endereço",
    clinical: "Clínico",
    department: "Subsistema",
    division: "Especialidade",
    codeForm: "Número de identificação da amostra",
    bodyPart: "Papel",
    resultTemplate: "Exemplo de leitura de resultados",
    resultPrint: "Imprimir formulário de resultados",
    language: "Linguagem",
    formName: "Nome do modelo",
    formResult: "Conclusão da amostra",
    createdAt: "Data de implementação",
    createdUser: "O artista",
    technicalProtocol: "PROCESSO TÉCNICO",
    imagingFindings: "DESCRIÇÃO DA IMAGEM",
    impression: "CONCLUSÃO, DIAGNÓSTICO",
    icd10Classification: "Classificação CID-10",
    gradingClassification: "Classificação, categorização",
    differentialDiagnosis: "diagnóstico diferencial",
    recommendationsCounseling: "RECOMENDAÇÕES E CONSELHOS",
    illustrativeImages: "ILUSTRAÇÃO",
    doctor: "MÉDICO EXECUTOR",
    time: "Tempo",
    Result_Report: "Folha de resultados",
  },
  ru: {
    administrativeInfo: "АДМИНИСТРАТИВНАЯ ИНФОРМАЦИЯ",
    fullName: "Полное имя",
    gender: "Секс",
    age: "Годовалый",
    nationality: "Национальность",
    phone: "Телефон",
    email: "Электронная почта",
    patientId: "Номер PID пациента",
    sid: "Код SID",
    province: "Провинция/Город",
    district: "Район/Коммуна",
    address: "Адрес",
    clinical: "Клинический",
    department: "Подсистема",
    division: "Специальность",
    codeForm: "Идентификационный номер образца",
    bodyPart: "Часть",
    resultTemplate: "Пример прочтения результатов",
    resultPrint: "Распечатать форму результатов",
    language: "Язык",
    formName: "Название модели",
    formResult: "Заключение образца",
    createdAt: "Дата реализации",
    createdUser: "Исполнитель",
    technicalProtocol: "ТЕХНИЧЕСКИЙ ПРОЦЕСС",
    imagingFindings: "ОПИСАНИЕ ИЗОБРАЖЕНИЯ",
    impression: "ЗАКЛЮЧЕНИЕ, ДИАГНОЗ",
    icd10Classification: "Классификация МКБ-10",
    gradingClassification: "Оценка, классификация",
    differentialDiagnosis: "Дифференциальная диагностика",
    recommendationsCounseling: "РЕКОМЕНДАЦИИ И СОВЕТЫ",
    illustrativeImages: "ИЛЛЮСТРАЦИЯ",
    doctor: "ИСПОЛНЯЮЩИЙ ДОКТОР",
    time: "Время",
    Result_Report: "Лист результатов",
  },
  nl: {
    administrativeInfo: "ADMINISTRATIEVE INFORMATIE",
    fullName: "Volledige naam",
    gender: "Seks",
    age: "jaar oud",
    nationality: "Nationaliteit",
    phone: "Telefoon",
    email: "E-mail",
    patientId: "PID-patiëntnummer",
    sid: "SID-code",
    province: "Provincie/Stad",
    district: "Wijk/Gemeente",
    address: "Adres",
    clinical: "Klinisch",
    department: "Subsysteem",
    division: "Specialiteit",
    codeForm: "Monster identificatienummer",
    bodyPart: "Deel",
    resultTemplate: "Voorbeeld van het lezen van de resultaten",
    resultPrint: "Resultatenformulier afdrukken",
    language: "Taal",
    formName: "Modelnaam",
    formResult: "Conclusie van het monster",
    createdAt: "Datum van implementatie",
    createdUser: "De uitvoerder",
    technicalProtocol: "TECHNISCH PROCES",
    imagingFindings: "AFBEELDINGBESCHRIJVING",
    impression: "CONCLUSIE, DIAGNOSE",
    icd10Classification: "ICD-10-classificatie",
    gradingClassification: "Gradatie, classificatie",
    differentialDiagnosis: "Differentiële diagnose",
    recommendationsCounseling: "AANBEVELINGEN & ADVIES",
    illustrativeImages: "ILLUSTRATIE",
    doctor: "UITVOERENDE DOKTER",
    time: "Tijd",
    Result_Report: "Resultatenblad",
  },
  pl: {
    administrativeInfo: "INFORMACJE ADMINISTRACYJNE",
    fullName: "Pełne imię i nazwisko",
    gender: "Seks",
    age: "Rok",
    nationality: "Narodowość",
    phone: "Telefon",
    email: "E-mail",
    patientId: "Numer pacjenta PID",
    sid: "Kod SID",
    province: "Prowincja/Miasto",
    district: "Dzielnica/Gmina",
    address: "Adres",
    clinical: "Kliniczny",
    department: "Podsystem",
    division: "Specjalność",
    codeForm: "Numer identyfikacyjny próbki",
    bodyPart: "Część",
    resultTemplate: "Przykładowy odczyt wyników",
    resultPrint: "Wydrukuj formularz wyników",
    language: "Język",
    formName: "Nazwa modelu",
    formResult: "Wnioski z próby",
    createdAt: "Data wdrożenia",
    createdUser: "Wykonawca",
    technicalProtocol: "PROCES TECHNICZNY",
    imagingFindings: "OPIS OBRAZU",
    impression: "WNIOSKI, DIAGNOZA",
    icd10Classification: "Klasyfikacja ICD-10",
    gradingClassification: "Klasyfikowanie, klasyfikacja",
    differentialDiagnosis: "Diagnostyka różnicowa",
    recommendationsCounseling: "REKOMENDACJE I PORADY",
    illustrativeImages: "ILUSTRACJA",
    doctor: "WYKONUJĄCY LEKARZ",
    time: "Czas",
    Result_Report: "Arkusz wyników",
  },
  sv: {
    administrativeInfo: "ADMINISTRATIV INFORMATION",
    fullName: "Fullständigt namn",
    gender: "Sex",
    age: "År gammal",
    nationality: "Nationalitet",
    phone: "Telefon",
    email: "E-post",
    patientId: "PID-patientnummer",
    sid: "SID-kod",
    province: "Provins/Stad",
    district: "Valkrets/kommun",
    address: "Adress",
    clinical: "Klinisk",
    department: "Delsystem",
    division: "Specialitet",
    codeForm: "Providentifieringsnummer",
    bodyPart: "Del",
    resultTemplate: "Exempelavläsning av resultat",
    resultPrint: "Skriv ut resultatformulär",
    language: "Språk",
    formName: "Modellnamn",
    formResult: "Slutsats av urvalet",
    createdAt: "Datum för implementering",
    createdUser: "Artisten",
    technicalProtocol: "TEKNISK PROCESS",
    imagingFindings: "BILDBESKRIVNING",
    impression: "SLUTSATS, DIAGNOS",
    icd10Classification: "ICD-10-klassificering",
    gradingClassification: "Gradering, klassificering",
    differentialDiagnosis: "Differentialdiagnos",
    recommendationsCounseling: "REKOMMENDATIONER OCH RÅD",
    illustrativeImages: "ILLUSTRATION",
    doctor: "UTÖVANDE LÄKARE",
    time: "Tid",
    Result_Report: "Resultatlista",
  },
  no: {
    administrativeInfo: "ADMINISTRATIV INFORMASJON",
    fullName: "Fullt navn",
    gender: "Kjønn",
    age: "År gammel",
    nationality: "Nasjonalitet",
    phone: "Telefon",
    email: "E-post",
    patientId: "PID-pasientnummer",
    sid: "SID-kode",
    province: "Provins/by",
    district: "Valgkrets/kommune",
    address: "Adresse",
    clinical: "Klinisk",
    department: "Delsystem",
    division: "Spesialitet",
    codeForm: "Prøveidentifikasjonsnummer",
    bodyPart: "Del",
    resultTemplate: "Eksempelavlesning av resultater",
    resultPrint: "Skriv ut resultatskjema",
    language: "Språk",
    formName: "Modellnavn",
    formResult: "Konklusjon av utvalget",
    createdAt: "Implementeringsdato",
    createdUser: "Utøveren",
    technicalProtocol: "TEKNISK PROSESS",
    imagingFindings: "BILDEBESKRIVELSE",
    impression: "KONKLUSJON, DIAGNOSE",
    icd10Classification: "ICD-10-klassifisering",
    gradingClassification: "Karaktersetting, klassifisering",
    differentialDiagnosis: "Differensialdiagnose",
    recommendationsCounseling: "ANBEFALINGER OG RÅD",
    illustrativeImages: "ILLUSTRASJON",
    doctor: "UTFØRENDE LEGE",
    time: "Tid",
    Result_Report: "Resultatark",
  },
  da: {
    administrativeInfo: "ADMINISTRATIVE OPLYSNINGER",
    fullName: "Fulde navn",
    gender: "Køn",
    age: "År gammel",
    nationality: "Nationalitet",
    phone: "Telefon",
    email: "E-mail",
    patientId: "PID-patientnummer",
    sid: "SID-kode",
    province: "Provins/By",
    district: "Valgkreds/Kommune",
    address: "Adresse",
    clinical: "Klinisk",
    department: "Delsystem",
    division: "Specialitet",
    codeForm: "Prøveidentifikationsnummer",
    bodyPart: "Del",
    resultTemplate: "Eksempelaflæsning af resultater",
    resultPrint: "Udskriv resultatformular",
    language: "Sprog",
    formName: "Modelnavn",
    formResult: "Konklusion af stikprøven",
    createdAt: "Implementeringsdato",
    createdUser: "Udøveren",
    technicalProtocol: "TEKNISK PROCES",
    imagingFindings: "BILLEDBESKRIVELSE",
    impression: "KONKLUSION, DIAGNOSE",
    icd10Classification: "ICD-10-klassifikation",
    gradingClassification: "Gradering, klassificering",
    differentialDiagnosis: "Differentialdiagnose",
    recommendationsCounseling: "ANBEFALINGER OG RÅDGIVNING",
    illustrativeImages: "ILLUSTRATION",
    doctor: "UDØVENDE LÆGE",
    time: "Tid",
    Result_Report: "Resultatark",
  },
  fi: {
    administrativeInfo: "HALLINNOLLISET TIEDOT",
    fullName: "Koko nimi",
    gender: "Seksi",
    age: "Vuoden vanha",
    nationality: "Kansalaisuus",
    phone: "Puhelin",
    email: "Sähköposti",
    patientId: "PID-potilasnumero",
    sid: "SID-koodi",
    province: "Maakunta/kaupunki",
    district: "Seurakunta/kunta",
    address: "Osoite",
    clinical: "Kliininen",
    department: "Alijärjestelmä",
    division: "Erikoisuus",
    codeForm: "Näytteen tunnistenumero",
    bodyPart: "Osa",
    resultTemplate: "Tulosten näyteluku",
    resultPrint: "Tulosta tuloslomake",
    language: "Kieli",
    formName: "Mallin nimi",
    formResult: "Otoksen päätelmät",
    createdAt: "Täytäntöönpanopäivä",
    createdUser: "Esiintyjä",
    technicalProtocol: "TEKNINEN PROSESSI",
    imagingFindings: "KUVAN KUVAUS",
    impression: "JOHTOPÄÄTÖS, DIAGNOOSI",
    icd10Classification: "ICD-10-luokitus",
    gradingClassification: "Arvostelu, luokittelu",
    differentialDiagnosis: "Erotusdiagnoosi",
    recommendationsCounseling: "SUOSITUKSET JA NEUVOJA",
    illustrativeImages: "KUVA",
    doctor: "SUORITTAVA LÄÄKÄRI",
    time: "Aika",
    Result_Report: "Tuloslomake",
  },
  el: {
    administrativeInfo: "ΔΙΟΙΚΗΤΙΚΕΣ ΠΛΗΡΟΦΟΡΙΕΣ",
    fullName: "Ονοματεπώνυμο",
    gender: "Φύλο",
    age: "Ένα χρόνο",
    nationality: "Ιθαγένεια",
    phone: "Τηλέφωνο",
    email: "E-mail",
    patientId: "Αριθμός ασθενούς PID",
    sid: "Κωδικός SID",
    province: "Επαρχία/Πόλη",
    district: "Περιφέρεια/Κοινότητα",
    address: "Διεύθυνση",
    clinical: "Κλινικός",
    department: "Υποσύστημα",
    division: "Ειδικότητα",
    codeForm: "Αριθμός αναγνώρισης δείγματος",
    bodyPart: "Μέρος",
    resultTemplate: "Δείγμα ανάγνωσης αποτελεσμάτων",
    resultPrint: "Εκτύπωση φόρμας αποτελεσμάτων",
    language: "Γλώσσα",
    formName: "Όνομα μοντέλου",
    formResult: "Συμπέρασμα του δείγματος",
    createdAt: "Ημερομηνία εφαρμογής",
    createdUser: "Ο ερμηνευτής",
    technicalProtocol: "ΤΕΧΝΙΚΗ ΔΙΑΔΙΚΑΣΙΑ",
    imagingFindings: "ΠΕΡΙΓΡΑΦΗ ΕΙΚΟΝΑΣ",
    impression: "ΣΥΜΠΕΡΑΣΜΑ, ΔΙΑΓΝΩΣΗ",
    icd10Classification: "Ταξινόμηση ICD-10",
    gradingClassification: "Βαθμολόγηση, ταξινόμηση",
    differentialDiagnosis: "Διαφορική διάγνωση",
    recommendationsCounseling: "ΣΥΣΤΑΣΕΙΣ & ΣΥΜΒΟΥΛΕΣ",
    illustrativeImages: "ΕΙΚΟΝΑ",
    doctor: "ΕΡΓΑΖΟΜΕΝΟΣ ΓΙΑΤΡΟΣ",
    time: "Φορά",
    Result_Report: "Φύλλο αποτελεσμάτων",
  },
  cs: {
    administrativeInfo: "ADMINISTRATIVNÍ INFORMACE",
    fullName: "Celé jméno",
    gender: "Sex",
    age: "Rok starý",
    nationality: "Státní příslušnost",
    phone: "Telefon",
    email: "E-mail",
    patientId: "Číslo pacienta s PID",
    sid: "SID kód",
    province: "Provincie/Město",
    district: "Okres/obec",
    address: "Adresa",
    clinical: "Klinický",
    department: "Subsystém",
    division: "Specialita",
    codeForm: "Identifikační číslo vzorku",
    bodyPart: "Část",
    resultTemplate: "Ukázka odečtu výsledků",
    resultPrint: "Vytiskněte formulář s výsledky",
    language: "Jazyk",
    formName: "Název modelu",
    formResult: "Závěr vzorku",
    createdAt: "Datum implementace",
    createdUser: "Umělec",
    technicalProtocol: "TECHNICKÝ POSTUP",
    imagingFindings: "POPIS OBRÁZKU",
    impression: "ZÁVĚR, DIAGNÓZA",
    icd10Classification: "Klasifikace MKN-10",
    gradingClassification: "Hodnocení, klasifikace",
    differentialDiagnosis: "Diferenciální diagnostika",
    recommendationsCounseling: "DOPORUČENÍ A RADY",
    illustrativeImages: "ILUSTRACE",
    doctor: "VYKONÁVAJÍCÍ LÉKAŘ",
    time: "Čas",
    Result_Report: "Výsledková listina",
  },
  hu: {
    administrativeInfo: "ADMINISZTRATÍV INFORMÁCIÓK",
    fullName: "Teljes név",
    gender: "Szex",
    age: "éves",
    nationality: "Állampolgárság",
    phone: "Telefon",
    email: "Email",
    patientId: "PID betegszám",
    sid: "SID-kód",
    province: "Tartomány/Város",
    district: "Egyházközség/Község",
    address: "Cím",
    clinical: "Klinikai",
    department: "Alrendszer",
    division: "Különlegesség",
    codeForm: "Minta azonosító száma",
    bodyPart: "Rész",
    resultTemplate: "Az eredmények mintaolvasása",
    resultPrint: "Eredményűrlap nyomtatása",
    language: "Nyelv",
    formName: "Modell neve",
    formResult: "A minta következtetése",
    createdAt: "Végrehajtás dátuma",
    createdUser: "Az előadóművész",
    technicalProtocol: "TECHNIKAI FOLYAMAT",
    imagingFindings: "KÉP LEÍRÁSA",
    impression: "KÖVETKEZTETÉS, DIAGNÓZIS",
    icd10Classification: "ICD-10 osztályozás",
    gradingClassification: "Osztályozás, osztályozás",
    differentialDiagnosis: "Differenciáldiagnózis",
    recommendationsCounseling: "AJÁNLÁSOK ÉS TANÁCSOK",
    illustrativeImages: "ÁBRA",
    doctor: "TELJESÍTŐ ORVOS",
    time: "Idő",
    Result_Report: "Eredménylap",
  },
  ro: {
    administrativeInfo: "INFORMAȚII ADMINISTRATIVE",
    fullName: "Numele complet",
    gender: "Sex",
    age: "De ani",
    nationality: "Naţionalitate",
    phone: "Telefon",
    email: "E-mail",
    patientId: "Numărul pacientului cu IDP",
    sid: "Cod SID",
    province: "Provincie/Oraș",
    district: "Secție/Comună",
    address: "Adresa",
    clinical: "Clinic",
    department: "Subsistem",
    division: "Specialitate",
    codeForm: "Numărul de identificare al eșantionului",
    bodyPart: "Parte",
    resultTemplate: "Citirea eșantionului de rezultate",
    resultPrint: "Formular de imprimare a rezultatelor",
    language: "Limbă",
    formName: "Numele modelului",
    formResult: "Concluzia eșantionului",
    createdAt: "Data implementării",
    createdUser: "Interpretul",
    technicalProtocol: "PROCES TEHNIC",
    imagingFindings: "DESCRIEREA IMAGINII",
    impression: "CONCLUZIE, DIAGNOSTIC",
    icd10Classification: "Clasificarea ICD-10",
    gradingClassification: "Clasificare, clasificare",
    differentialDiagnosis: "Diagnostic diferențial",
    recommendationsCounseling: "RECOMANDĂRI ȘI SFATURI",
    illustrativeImages: "ILUSTRARE",
    doctor: "MEDIC PERFORMANT",
    time: "Timp",
    Result_Report: "Fișă de rezultate",
  },
  bg: {
    administrativeInfo: "АДМИНИСТРАТИВНА ИНФОРМАЦИЯ",
    fullName: "Пълно име",
    gender: "Секс",
    age: "Година на възраст",
    nationality: "Националност",
    phone: "Телефон",
    email: "Имейл",
    patientId: "Номер на пациент с ПИД",
    sid: "SID код",
    province: "Провинция/Град",
    district: "Район/Комуна",
    address: "Адрес",
    clinical: "Клинични",
    department: "Подсистема",
    division: "Специалност",
    codeForm: "Идентификационен номер на пробата",
    bodyPart: "Част",
    resultTemplate: "Примерно отчитане на резултатите",
    resultPrint: "Формуляр за печат на резултати",
    language: "Език",
    formName: "Име на модела",
    formResult: "Заключение на извадката",
    createdAt: "Дата на изпълнение",
    createdUser: "Изпълнителят",
    technicalProtocol: "ТЕХНИЧЕСКИ ПРОЦЕС",
    imagingFindings: "ОПИСАНИЕ НА ИЗОБРАЖЕНИЕТО",
    impression: "ЗАКЛЮЧЕНИЕ, ДИАГНОЗА",
    icd10Classification: "Класификация на МКБ-10",
    gradingClassification: "Оценяване, класификация",
    differentialDiagnosis: "Диференциална диагноза",
    recommendationsCounseling: "ПРЕПОРЪКИ И СЪВЕТИ",
    illustrativeImages: "ИЛЮСТРАЦИЯ",
    doctor: "ИЗПЪЛНИТЕЛЕН ЛЕКАР",
    time: "Време",
    Result_Report: "Лист с резултати",
  },
  sk: {
    administrativeInfo: "ADMINISTRATÍVNE INFORMÁCIE",
    fullName: "Celé meno",
    gender: "Pohlavie",
    age: "Rok starý",
    nationality: "Štátna príslušnosť",
    phone: "Telefón",
    email: "E-mail",
    patientId: "Číslo pacienta s PID",
    sid: "Kód SID",
    province: "Provincia/Mesto",
    district: "Obvod/Obec",
    address: "Adresa",
    clinical: "Klinické",
    department: "Subsystém",
    division: "Špecializácia",
    codeForm: "Identifikačné číslo vzorky",
    bodyPart: "Časť",
    resultTemplate: "Ukážka odčítania výsledkov",
    resultPrint: "Tlač výsledkov",
    language: "Jazyk",
    formName: "Názov modelu",
    formResult: "Záver vzorky",
    createdAt: "Dátum implementácie",
    createdUser: "Umelec",
    technicalProtocol: "TECHNICKÝ POSTUP",
    imagingFindings: "POPIS OBRÁZKA",
    impression: "ZÁVER, DIAGNÓZA",
    icd10Classification: "Klasifikácia ICD-10",
    gradingClassification: "Známkovanie, klasifikácia",
    differentialDiagnosis: "Diferenciálna diagnostika",
    recommendationsCounseling: "ODPORÚČANIA A RADY",
    illustrativeImages: "ILUSTRÁCIA",
    doctor: "VYKONÁVAJÚCI LEKÁR",
    time: "Čas",
    Result_Report: "Výsledková listina",
  },
  sl: {
    administrativeInfo: "ADMINISTRATIVNE INFORMACIJE",
    fullName: "Polno ime",
    gender: "Seks",
    age: "Leto star",
    nationality: "Državljanstvo",
    phone: "Telefon",
    email: "E-pošta",
    patientId: "Številka pacienta s PID",
    sid: "Koda SID",
    province: "Pokrajina/mesto",
    district: "Okrožje/občina",
    address: "Naslov",
    clinical: "Klinično",
    department: "Podsistem",
    division: "Specialnost",
    codeForm: "Identifikacijska številka vzorca",
    bodyPart: "Del",
    resultTemplate: "Vzorec odčitavanja rezultatov",
    resultPrint: "Obrazec za tiskanje rezultatov",
    language: "Jezik",
    formName: "Ime modela",
    formResult: "Zaključek vzorca",
    createdAt: "Datum izvedbe",
    createdUser: "Izvajalec",
    technicalProtocol: "TEHNIČNI POSTOPEK",
    imagingFindings: "OPIS SLIKE",
    impression: "ZAKLJUČEK, DIAGNOZA",
    icd10Classification: "Klasifikacija MKB-10",
    gradingClassification: "Razvrščanje, klasifikacija",
    differentialDiagnosis: "Diferencialna diagnoza",
    recommendationsCounseling: "PRIPOROČILA IN NASVETI",
    illustrativeImages: "ILUSTRACIJA",
    doctor: "IZVAJALNI ZDRAVNIK",
    time: "Čas",
    Result_Report: "Rezultatni list",
  },
  hr: {
    administrativeInfo: "ADMINISTRATIVNE INFORMACIJE",
    fullName: "Puno ime",
    gender: "Seks",
    age: "Star godinu dana",
    nationality: "Nacionalnost",
    phone: "Telefon",
    email: "E-pošta",
    patientId: "Broj pacijenta s PID-om",
    sid: "SID kod",
    province: "Pokrajina/Grad",
    district: "Odjel/općina",
    address: "Adresa",
    clinical: "Klinički",
    department: "Podsustav",
    division: "Specijalitet",
    codeForm: "Identifikacijski broj uzorka",
    bodyPart: "Dio",
    resultTemplate: "Primjer očitavanja rezultata",
    resultPrint: "Ispis rezultata",
    language: "Jezik",
    formName: "Naziv modela",
    formResult: "Zaključak uzorka",
    createdAt: "Datum provedbe",
    createdUser: "Izvođač",
    technicalProtocol: "TEHNIČKI POSTUPAK",
    imagingFindings: "OPIS SLIKE",
    impression: "ZAKLJUČAK, DIJAGNOZA",
    icd10Classification: "Klasifikacija ICD-10",
    gradingClassification: "Ocjenjivanje, klasifikacija",
    differentialDiagnosis: "Diferencijalna dijagnoza",
    recommendationsCounseling: "PREPORUKE I SAVJETI",
    illustrativeImages: "ILUSTRACIJA",
    doctor: "LIJEČNIK IZVEDBE",
    time: "Vrijeme",
    Result_Report: "Rezultatski list",
  },
  uk: {
    administrativeInfo: "АДМІНІСТРАТИВНА ІНФОРМАЦІЯ",
    fullName: "Повне ім'я",
    gender: "Секс",
    age: "Річний",
    nationality: "Громадянство",
    phone: "Телефон",
    email: "Електронна пошта",
    patientId: "Номер пацієнта з ПІД",
    sid: "Код SID",
    province: "Область/Місто",
    district: "Район/Комуна",
    address: "Адреса",
    clinical: "Клінічний",
    department: "Підсистема",
    division: "Спеціальність",
    codeForm: "Ідентифікаційний номер зразка",
    bodyPart: "Частина",
    resultTemplate: "Зразок зчитування результатів",
    resultPrint: "Форма для друку результатів",
    language: "Мова",
    formName: "Назва моделі",
    formResult: "Висновок зразка",
    createdAt: "Дата впровадження",
    createdUser: "Виконавець",
    technicalProtocol: "ТЕХНІЧНИЙ ПРОЦЕС",
    imagingFindings: "ОПИС ЗОБРАЖЕННЯ",
    impression: "ВИСНОВОК, ДІАГНОЗ",
    icd10Classification: "Класифікація МКХ-10",
    gradingClassification: "Оцінювання, класифікація",
    differentialDiagnosis: "Диференціальна діагностика",
    recommendationsCounseling: "РЕКОМЕНДАЦІЇ ТА ПОРАДИ",
    illustrativeImages: "ІЛЮСТРАЦІЯ",
    doctor: "ВИКОНУЮЧИЙ ЛІКАР",
    time: "Час",
    Result_Report: "Результатний лист",
  },
  sr: {
    administrativeInfo: "АДМИНИСТРАТИВНЕ ИНФОРМАЦИЈЕ",
    fullName: "Пуно име",
    gender: "Секс",
    age: "Година стар",
    nationality: "Националност",
    phone: "Телефон",
    email: "Е-пошта",
    patientId: "Број пацијента са ПИД-ом",
    sid: "SID код",
    province: "Покрајина/Град",
    district: "Одељење/Комуна",
    address: "Адреса",
    clinical: "Клинички",
    department: "Подсистем",
    division: "Специјалност",
    codeForm: "Идентификациони број узорка",
    bodyPart: "Део",
    resultTemplate: "Пример очитавања резултата",
    resultPrint: "Одштампајте образац за резултате",
    language: "Језик",
    formName: "Назив модела",
    formResult: "Закључак узорка",
    createdAt: "Датум имплементације",
    createdUser: "Извођач",
    technicalProtocol: "ТЕХНИЧКИ ПРОЦЕС",
    imagingFindings: "ОПИС СЛИКЕ",
    impression: "ЗАКЉУЧАК, ДИЈАГНОЗА",
    icd10Classification: "Класификација МКБ-10",
    gradingClassification: "Оцењивање, класификација",
    differentialDiagnosis: "Диференцијална дијагноза",
    recommendationsCounseling: "ПРЕПОРУКЕ И САВЕТИ",
    illustrativeImages: "ИЛУСТРАЦИЈА",
    doctor: "ИЗВОЂАЧКИ ДОКТОР",
    time: "Време",
    Result_Report: "Лист са резултатима",
  },
  lt: {
    administrativeInfo: "ADMINISTRACINĖ INFORMACIJA",
    fullName: "Pilnas vardas",
    gender: "Seksas",
    age: "Metų senumo",
    nationality: "Tautybė",
    phone: "Telefonas",
    email: "El. paštas",
    patientId: "PID paciento numeris",
    sid: "SID kodas",
    province: "Provincija / Miestas",
    district: "Rajonas/komuna",
    address: "Adresas",
    clinical: "Klinikinis",
    department: "Posistemė",
    division: "Specialybė",
    codeForm: "Mėginio identifikavimo numeris",
    bodyPart: "Dalis",
    resultTemplate: "Rezultatų pavyzdžio skaitymas",
    resultPrint: "Spausdinti rezultatų formą",
    language: "Kalba",
    formName: "Modelio pavadinimas",
    formResult: "Imties išvada",
    createdAt: "Įgyvendinimo data",
    createdUser: "Atlikėjas",
    technicalProtocol: "TECHNINIS PROCESAS",
    imagingFindings: "VAIZDO APRAŠYMAS",
    impression: "IŠVADA, DIAGNOZĖ",
    icd10Classification: "TLK-10 klasifikacija",
    gradingClassification: "Įvertinimas, klasifikavimas",
    differentialDiagnosis: "Diferencinė diagnozė",
    recommendationsCounseling: "REKOMENDACIJOS IR PATARIMAI",
    illustrativeImages: "ILIUSTRACIJA",
    doctor: "ATLIEKAMASIS GYDYTOJAS",
    time: "Laikas",
    Result_Report: "Rezultatų lapas",
  },
  lv: {
    administrativeInfo: "ADMINISTRATĪVĀ INFORMĀCIJA",
    fullName: "Pilns vārds",
    gender: "Sekss",
    age: "Gadu vecs",
    nationality: "Valstspiederība",
    phone: "Tālrunis",
    email: "E-pasts",
    patientId: "PID pacienta numurs",
    sid: "SID kods",
    province: "Province/Pilsēta",
    district: "Rajons/komūna",
    address: "Adrese",
    clinical: "Klīniskā",
    department: "Apakšsistēma",
    division: "Specialitāte",
    codeForm: "Parauga identifikācijas numurs",
    bodyPart: "Daļa",
    resultTemplate: "Rezultātu parauga nolasīšana",
    resultPrint: "Drukāt rezultātu veidlapu",
    language: "Valoda",
    formName: "Modeļa nosaukums",
    formResult: "Izlases secinājums",
    createdAt: "Īstenošanas datums",
    createdUser: "Izpildītājs",
    technicalProtocol: "TEHNISKAIS PROCESS",
    imagingFindings: "ATTĒLA APRAKSTS",
    impression: "SECINĀJUMS, DIAGNOZE",
    icd10Classification: "ICD-10 klasifikācija",
    gradingClassification: "Vērtēšana, klasifikācija",
    differentialDiagnosis: "Diferenciālā diagnoze",
    recommendationsCounseling: "IETEIKUMI UN PADOMI",
    illustrativeImages: "ILUSTRĀCIJA",
    doctor: "IZPILDĀJOŠAIS ĀRSTS",
    time: "Laiks",
    Result_Report: "Rezultātu lapa",
  },
  et: {
    administrativeInfo: "ADMINISTRATIIVNE TEAVE",
    fullName: "Täisnimi",
    gender: "Seks",
    age: "Aastane",
    nationality: "Rahvus",
    phone: "Telefon",
    email: "E-post",
    patientId: "PID-patsiendi number",
    sid: "SID-kood",
    province: "Provints/linn",
    district: "Kogudus/vald",
    address: "Aadress",
    clinical: "Kliiniline",
    department: "Allsüsteem",
    division: "Eriala",
    codeForm: "Proovi identifitseerimisnumber",
    bodyPart: "Osa",
    resultTemplate: "Tulemuste näidislugemine",
    resultPrint: "Prindi tulemuste vorm",
    language: "Keel",
    formName: "Mudeli nimi",
    formResult: "Valimi kokkuvõte",
    createdAt: "Rakendamise kuupäev",
    createdUser: "Esineja",
    technicalProtocol: "TEHNILINE PROTSESS",
    imagingFindings: "PILDI KIRJELDUS",
    impression: "JÄRELDUS, DIAGNOOS",
    icd10Classification: "RHK-10 klassifikatsioon",
    gradingClassification: "Hindamine, liigitamine",
    differentialDiagnosis: "Diferentsiaaldiagnoos",
    recommendationsCounseling: "SOOVITUSED JA NÕUANDED",
    illustrativeImages: "ILLUSTRATSIOON",
    doctor: "ESINEV ARST",
    time: "Aeg",
    Result_Report: "Tulemuste leht",
  },
  "es-419": {
    administrativeInfo: "INFORMACIÓN ADMINISTRATIVA",
    fullName: "Nombre completo",
    gender: "Sexo",
    age: "Años de edad",
    nationality: "Nacionalidad",
    phone: "Teléfono",
    email: "Correo electrónico",
    patientId: "número de paciente con EPI",
    sid: "Código SID",
    province: "Provincia/Ciudad",
    district: "Barrio/Comuna",
    address: "DIRECCIÓN",
    clinical: "Clínico",
    department: "Subsistema",
    division: "Especialidad",
    codeForm: "Número de identificación de la muestra",
    bodyPart: "Parte",
    resultTemplate: "Ejemplo de lectura de resultados",
    resultPrint: "Formulario de resultados de impresión",
    language: "Idioma",
    formName: "Nombre del modelo",
    formResult: "Conclusión de la muestra",
    createdAt: "Fecha de implementación",
    createdUser: "El intérprete",
    technicalProtocol: "PROCESO TÉCNICO",
    imagingFindings: "DESCRIPCIÓN DE LA IMAGEN",
    impression: "CONCLUSIÓN, DIAGNÓSTICO",
    icd10Classification: "Clasificación CIE-10",
    gradingClassification: "Calificación, clasificación",
    differentialDiagnosis: "Diagnóstico diferencial",
    recommendationsCounseling: "RECOMENDACIONES Y CONSEJOS",
    illustrativeImages: "ILUSTRACIÓN",
    doctor: "MÉDICO ACTUANDO",
    time: "Tiempo",
    Result_Report: "Hoja de resultados",
  },
  "pt-BR": {
    administrativeInfo: "INFORMAÇÕES ADMINISTRATIVAS",
    fullName: "Nome completo",
    gender: "Sexo",
    age: "Anos",
    nationality: "Nacionalidade",
    phone: "Telefone",
    email: "E-mail",
    patientId: "número do paciente PID",
    sid: "Código SID",
    province: "Província/Cidade",
    district: "Bairro/Comuna",
    address: "Endereço",
    clinical: "Clínico",
    department: "Subsistema",
    division: "Especialidade",
    codeForm: "Número de identificação da amostra",
    bodyPart: "Papel",
    resultTemplate: "Exemplo de leitura de resultados",
    resultPrint: "Imprimir formulário de resultados",
    language: "Linguagem",
    formName: "Nome do modelo",
    formResult: "Conclusão da amostra",
    createdAt: "Data de implementação",
    createdUser: "O artista",
    technicalProtocol: "PROCESSO TÉCNICO",
    imagingFindings: "DESCRIÇÃO DA IMAGEM",
    impression: "CONCLUSÃO, DIAGNÓSTICO",
    icd10Classification: "Classificação CID-10",
    gradingClassification: "Classificação, categorização",
    differentialDiagnosis: "diagnóstico diferencial",
    recommendationsCounseling: "RECOMENDAÇÕES E CONSELHOS",
    illustrativeImages: "ILUSTRAÇÃO",
    doctor: "MÉDICO EXECUTOR",
    time: "Tempo",
    Result_Report: "Folha de resultados",
  },
  ht: {
    administrativeInfo: "ENFÒMASYON ADMINISTRATIF",
    fullName: "Non konplè",
    gender: "Sèks",
    age: "Ane",
    nationality: "Nasyonalite",
    phone: "Telefòn",
    email: "Imèl",
    patientId: "Nimewo pasyan PID",
    sid: "Kòd SID",
    province: "Pwovens/Vil",
    district: "Pawas/Komin",
    address: "Adrès",
    clinical: "Klinik",
    department: "Sous-sistèm",
    division: "Espesyalite",
    codeForm: "Nimewo idantifikasyon echantiyon an",
    bodyPart: "Pati",
    resultTemplate: "Lekti echantiyon rezilta yo",
    resultPrint: "Enprime fòm rezilta yo",
    language: "Lang",
    formName: "Non modèl",
    formResult: "Konklizyon echantiyon an",
    createdAt: "Dat aplikasyon an",
    createdUser: "Pèfòmè a",
    technicalProtocol: "PWOSESIS TEKNIK",
    imagingFindings: "DESKRIPSYON IMAJ",
    impression: "KONKLIZYON, DYAGNOSIK",
    icd10Classification: "Klasifikasyon ICD-10",
    gradingClassification: "Klasifikasyon, nòt",
    differentialDiagnosis: "Dyagnostik diferansyèl",
    recommendationsCounseling: "REKOMANDASYON AK KONSÈY",
    illustrativeImages: "ILUSTRASYON",
    doctor: "DOKTÈ KI AP PÈFÒME",
    time: "Tan",
    Result_Report: "Fèy rezilta",
  },
  ar: {
    administrativeInfo: "المعلومات الإدارية",
    fullName: "الاسم الكامل",
    gender: "الجنس",
    age: "سنة",
    nationality: "جنسية",
    phone: "هاتف",
    email: "بريد إلكتروني",
    patientId: "رقم المريض PID",
    sid: "رمز SID",
    province: "المقاطعة/المدينة",
    district: "الحي/البلدية",
    address: "عنوان",
    clinical: "سريري",
    department: "النظام الفرعي",
    division: "التخصص",
    codeForm: "رقم تعريف العينة",
    bodyPart: "جزء",
    resultTemplate: "قراءة عينة من النتائج",
    resultPrint: "نموذج طباعة النتائج",
    language: "لغة",
    formName: "اسم الموديل",
    formResult: "استنتاج العينة",
    createdAt: "تاريخ التنفيذ",
    createdUser: "المؤدي",
    technicalProtocol: "العملية الفنية",
    imagingFindings: "وصف الصورة",
    impression: "الاستنتاج والتشخيص",
    icd10Classification: "تصنيف ICD-10",
    gradingClassification: "التصنيف والتصنيف",
    differentialDiagnosis: "التشخيص التفريقي",
    recommendationsCounseling: "التوصيات والنصائح",
    illustrativeImages: "توضيح",
    doctor: "طبيب الأداء",
    time: "وقت",
    Result_Report: "ورقة النتائج",
  },
  fa: {
    administrativeInfo: "اطلاعات اداری",
    fullName: "نام کامل",
    gender: "سکس",
    age: "ساله",
    nationality: "ملیت",
    phone: "تلفن",
    email: "ایمیل",
    patientId: "شماره بیمار مبتلا به PID",
    sid: "کد SID",
    province: "استان/شهر",
    district: "بخش/کمون",
    address: "آدرس",
    clinical: "بالینی",
    department: "زیرسیستم",
    division: "تخصص",
    codeForm: "شماره شناسایی نمونه",
    bodyPart: "قسمت",
    resultTemplate: "نمونه قرائت نتایج",
    resultPrint: "فرم نتایج چاپ",
    language: "زبان",
    formName: "نام مدل",
    formResult: "نتیجه‌گیری از نمونه",
    createdAt: "تاریخ اجرا",
    createdUser: "مجری",
    technicalProtocol: "فرآیند فنی",
    imagingFindings: "شرح تصویر",
    impression: "نتیجه‌گیری، تشخیص",
    icd10Classification: "طبقه‌بندی ICD-10",
    gradingClassification: "درجه‌بندی، طبقه‌بندی",
    differentialDiagnosis: "تشخیص افتراقی",
    recommendationsCounseling: "توصیه‌ها و توصیه‌ها",
    illustrativeImages: "تصویرسازی",
    doctor: "پزشک مجری",
    time: "زمان",
    Result_Report: "برگه نتایج",
  },
  tr: {
    administrativeInfo: "İDARİ BİLGİLER",
    fullName: "Ad Soyad",
    gender: "Seks",
    age: "Yaşında",
    nationality: "Milliyet",
    phone: "Telefon",
    email: "E-posta",
    patientId: "PID hasta numarası",
    sid: "SID Kodu",
    province: "İl/Şehir",
    district: "Mahalle/Komün",
    address: "Adres",
    clinical: "Klinik",
    department: "Alt sistem",
    division: "Uzmanlık",
    codeForm: "Örnek tanımlama numarası",
    bodyPart: "Parça",
    resultTemplate: "Sonuçların örnek okuması",
    resultPrint: "Sonuç formunu yazdır",
    language: "Dil",
    formName: "Model adı",
    formResult: "Örneklemin sonucu",
    createdAt: "Uygulama tarihi",
    createdUser: "İcracı",
    technicalProtocol: "TEKNİK SÜREÇ",
    imagingFindings: "GÖRÜNTÜ AÇIKLAMASI",
    impression: "SONUÇ, TANI",
    icd10Classification: "ICD-10 Sınıflandırması",
    gradingClassification: "Sınıflandırma, sınıflandırma",
    differentialDiagnosis: "Ayırıcı tanı",
    recommendationsCounseling: "ÖNERİLER VE TAVSİYELER",
    illustrativeImages: "RESİM",
    doctor: "GÖREVLİ DOKTOR",
    time: "Zaman",
    Result_Report: "Sonuç sayfası",
  },
  he: {
    administrativeInfo: "מידע אדמיניסטרטיבי",
    fullName: "שם מלא",
    gender: "מִין",
    age: "בן שנה",
    nationality: "אֶזרָחוּת",
    phone: "טֵלֵפוֹן",
    email: "אֶלֶקטרוֹנִי",
    patientId: "מספר מטופל PID",
    sid: "קוד SID",
    province: "מחוז/עיר",
    district: "רובע/קומונה",
    address: "כְּתוֹבֶת",
    clinical: "קליני",
    department: "תת-מערכת",
    division: "הִתמַחוּת",
    codeForm: "מספר זיהוי לדוגמה",
    bodyPart: "חֵלֶק",
    resultTemplate: "קריאת תוצאות לדוגמה",
    resultPrint: "הדפס טופס תוצאות",
    language: "שָׂפָה",
    formName: "שם הדגם",
    formResult: "מסקנת המדגם",
    createdAt: "תאריך היישום",
    createdUser: "המבצע",
    technicalProtocol: "תהליך טכני",
    imagingFindings: "תיאור התמונה",
    impression: "סיכום, אבחון",
    icd10Classification: "סיווג ICD-10",
    gradingClassification: "דירוג, סיווג",
    differentialDiagnosis: "אבחנה מבדלת",
    recommendationsCounseling: "המלצות ועצות",
    illustrativeImages: "אִיוּר",
    doctor: "רופא מבצע",
    time: "זְמַן",
    Result_Report: "גיליון תוצאות",
  },
  ur: {
    administrativeInfo: "انتظامی معلومات",
    fullName: "پورا نام",
    gender: "سیکس",
    age: "سالہ",
    nationality: "قومیت",
    phone: "فون",
    email: "ای میل",
    patientId: "پی آئی ڈی مریض نمبر",
    sid: "ایس آئی ڈی کوڈ",
    province: "صوبہ/شہر",
    district: "وارڈ/کمیون",
    address: "پتہ",
    clinical: "طبی",
    department: "ذیلی نظام",
    division: "خاصیت",
    codeForm: "نمونہ شناختی نمبر",
    bodyPart: "حصہ",
    resultTemplate: "نتائج کا نمونہ پڑھنا",
    resultPrint: "نتائج کا فارم پرنٹ کریں۔",
    language: "زبان",
    formName: "ماڈل کا نام",
    formResult: "نمونے کا اختتام",
    createdAt: "نفاذ کی تاریخ",
    createdUser: "اداکار",
    technicalProtocol: "تکنیکی عمل",
    imagingFindings: "تصویر کی تفصیل",
    impression: "نتیجہ، تشخیص",
    icd10Classification: "ICD-10 درجہ بندی",
    gradingClassification: "درجہ بندی، درجہ بندی",
    differentialDiagnosis: "امتیازی تشخیص",
    recommendationsCounseling: "سفارشات اور مشورہ",
    illustrativeImages: "مثال",
    doctor: "پرفارمنگ ڈاکٹر",
    time: "وقت",
    Result_Report: "رزلٹ شیٹ",
  },
  hi: {
    administrativeInfo: "प्रशासनिक जानकारी",
    fullName: "पूरा नाम",
    gender: "लिंग",
    age: "साल",
    nationality: "राष्ट्रीयता",
    phone: "फ़ोन",
    email: "ईमेल",
    patientId: "पीआईडी ​​रोगी संख्या",
    sid: "एसआईडी कोड",
    province: "प्रांत/शहर",
    district: "वार्ड/कम्यून",
    address: "पता",
    clinical: "क्लीनिकल",
    department: "सबसिस्टम",
    division: "स्पेशलिटी",
    codeForm: "नमूना पहचान संख्या",
    bodyPart: "भाग",
    resultTemplate: "परिणामों का नमूना पठन",
    resultPrint: "परिणाम प्रपत्र प्रिंट करें",
    language: "भाषा",
    formName: "मॉडल नाम",
    formResult: "नमूने का निष्कर्ष",
    createdAt: "कार्यान्वयन की तिथि",
    createdUser: "प्रदर्शन करने वाला",
    technicalProtocol: "तकनीकी प्रक्रिया",
    imagingFindings: "छवि विवरण",
    impression: "निष्कर्ष, निदान",
    icd10Classification: "आईसीडी-10 वर्गीकरण",
    gradingClassification: "ग्रेडिंग, वर्गीकरण",
    differentialDiagnosis: "क्रमानुसार रोग का निदान",
    recommendationsCounseling: "सिफारिशें और सलाह",
    illustrativeImages: "चित्रण",
    doctor: "प्रदर्शनकारी डॉक्टर",
    time: "समय",
    Result_Report: "परिणाम पत्रक",
  },
  bn: {
    administrativeInfo: "প্রশাসনিক তথ্য",
    fullName: "পুরো নাম",
    gender: "লিঙ্গ",
    age: "বছর বয়সী",
    nationality: "জাতীয়তা",
    phone: "ফোন",
    email: "ইমেইল",
    patientId: "পিআইডি রোগীর সংখ্যা",
    sid: "এসআইডি কোড",
    province: "প্রদেশ/শহর",
    district: "ওয়ার্ড/কমিউন",
    address: "জানুন",
    clinical: "ক্লিনিক্যাল",
    department: "সাবসিস্টেম",
    division: "বিশেষত্ব",
    codeForm: "নমুনা শনাক্তকরণ নম্বর",
    bodyPart: "অংশ",
    resultTemplate: "ফলাফলের নমুনা পঠন",
    resultPrint: "ফলাফল ফর্ম প্রিন্ট করুন",
    language: "ভাষা",
    formName: "মডেলের নাম",
    formResult: "নমুনার উপসংহার",
    createdAt: "বাস্তবায়নের তারিখ",
    createdUser: "অভিনয়শিল্পী",
    technicalProtocol: "প্রযুক্তিগত প্রক্রিয়া",
    imagingFindings: "ছবির বর্ণনা",
    impression: "উপসংহার, রোগ নির্ণয়",
    icd10Classification: "ICD-10 শ্রেণীবিভাগ",
    gradingClassification: "গ্রেডিং, শ্রেণীবিভাগ",
    differentialDiagnosis: "ডিফারেনশিয়াল ডায়াগনোসিস",
    recommendationsCounseling: "সুপারিশ এবং পরামর্শ",
    illustrativeImages: "চিত্রণ",
    doctor: "কর্মক্ষম ডাক্তার",
    time: "সময়",
    Result_Report: "ফলাফল পত্র",
  },
  ta: {
    administrativeInfo: "நிர்வாக தகவல்",
    fullName: "முழு பெயர்",
    gender: "செக்ஸ்",
    age: "வயது",
    nationality: "தேசியம்",
    phone: "தொலைபேசி",
    email: "மின்னஞ்சல்",
    patientId: "PID நோயாளி எண்",
    sid: "SID குறியீடு",
    province: "மாகாணம்/நகரம்",
    district: "வார்டு/கம்யூன்",
    address: "முகவரி",
    clinical: "மருத்துவம்",
    department: "துணை அமைப்பு",
    division: "சிறப்பு",
    codeForm: "மாதிரி அடையாள எண்",
    bodyPart: "பகுதி",
    resultTemplate: "முடிவுகளின் மாதிரி வாசிப்பு",
    resultPrint: "முடிவுகள் படிவத்தை அச்சிடுக",
    language: "மொழி",
    formName: "மாதிரி பெயர்",
    formResult: "மாதிரியின் முடிவு",
    createdAt: "செயல்படுத்தப்பட்ட தேதி",
    createdUser: "கலைஞர்",
    technicalProtocol: "தொழில்நுட்ப செயல்முறை",
    imagingFindings: "பட விளக்கம்",
    impression: "முடிவுரை, நோய் கண்டறிதல்",
    icd10Classification: "ICD-10 வகைப்பாடு",
    gradingClassification: "தரப்படுத்தல், வகைப்பாடு",
    differentialDiagnosis: "வேறுபட்ட நோயறிதல்",
    recommendationsCounseling: "பரிந்துரைகள் & ஆலோசனை",
    illustrativeImages: "விளக்கம்",
    doctor: "செயல்திறன் மருத்துவர்",
    time: "நேரம்",
    Result_Report: "முடிவு தாள்",
  },
  te: {
    administrativeInfo: "పరిపాలనా సమాచారం",
    fullName: "పూర్తి పేరు",
    gender: "సెక్స్",
    age: "సంవత్సరం వయస్సు",
    nationality: "జాతీయత",
    phone: "ఫోన్",
    email: "ఇ-మెయిల్",
    patientId: "PID రోగి సంఖ్య",
    sid: "SID కోడ్",
    province: "ప్రావిన్స్/నగరం",
    district: "వార్డు/కమ్యూన్",
    address: "చిరునామా",
    clinical: "క్లినికల్",
    department: "ఉపవ్యవస్థ",
    division: "ప్రత్యేకత",
    codeForm: "నమూనా గుర్తింపు సంఖ్య",
    bodyPart: "భాగం",
    resultTemplate: "ఫలితాల నమూనా పఠనం",
    resultPrint: "ఫలితాల ఫారమ్‌ను ముద్రించండి",
    language: "భాష",
    formName: "మోడల్ పేరు",
    formResult: "నమూనా యొక్క ముగింపు",
    createdAt: "అమలు తేదీ",
    createdUser: "ప్రదర్శకుడు",
    technicalProtocol: "సాంకేతిక ప్రక్రియ",
    imagingFindings: "చిత్ర వివరణ",
    impression: "ముగింపు, రోగ నిర్ధారణ",
    icd10Classification: "ICD-10 వర్గీకరణ",
    gradingClassification: "గ్రేడింగ్, వర్గీకరణ",
    differentialDiagnosis: "అవకలన నిర్ధారణ",
    recommendationsCounseling: "సిఫార్సులు & సలహా",
    illustrativeImages: "దృష్టాంతం",
    doctor: "పెర్ఫార్మింగ్ డాక్టర్",
    time: "సమయం",
    Result_Report: "ఫలితాల షీట్",
  },
  ml: {
    administrativeInfo: "അഡ്മിനിസ്ട്രേറ്റീവ് വിവരങ്ങൾ",
    fullName: "പൂർണ്ണമായ പേര്",
    gender: "സെക്സ്",
    age: "പ്രായം",
    nationality: "ദേശീയത",
    phone: "ഫോൺ",
    email: "ഇമെയിൽ",
    patientId: "PID രോഗി നമ്പർ",
    sid: "SID കോഡ്",
    province: "പ്രവിശ്യ/നഗരം",
    district: "വാർഡ്/കമ്മ്യൂൺ",
    address: "വിലാസം",
    clinical: "ക്ലിനിക്കൽ",
    department: "ഉപസിസ്റ്റം",
    division: "സ്പെഷ്യാലിറ്റി",
    codeForm: "സാമ്പിൾ തിരിച്ചറിയൽ നമ്പർ",
    bodyPart: "ഭാഗം",
    resultTemplate: "ഫലങ്ങളുടെ സാമ്പിൾ വായന",
    resultPrint: "ഫല ഫോം പ്രിന്റ് ചെയ്യുക",
    language: "ഭാഷ",
    formName: "മോഡലിന്റെ പേര്",
    formResult: "സാമ്പിളിന്റെ ഉപസംഹാരം",
    createdAt: "നടപ്പിലാക്കിയ തീയതി",
    createdUser: "അവതാരകൻ",
    technicalProtocol: "സാങ്കേതിക പ്രക്രിയ",
    imagingFindings: "ചിത്രത്തിന്റെ വിവരണം",
    impression: "ഉപസംഹാരം, രോഗനിർണയം",
    icd10Classification: "ഐസിഡി -10 വർഗ്ഗീകരണം",
    gradingClassification: "ഗ്രേഡിംഗ്, വർഗ്ഗീകരണം",
    differentialDiagnosis: "ഡിഫറൻഷ്യൽ ഡയഗ്നോസിസ്",
    recommendationsCounseling: "ശുപാർശകളും ഉപദേശവും",
    illustrativeImages: "ചിത്രീകരണം",
    doctor: "പെർഫോമിംഗ് ഡോക്ടർ",
    time: "സമയം",
    Result_Report: "ഫല ഷീറ്റ്",
  },
  pa: {
    administrativeInfo: "ਪ੍ਰਬੰਧਕੀ ਜਾਣਕਾਰੀ",
    fullName: "ਪੂਰਾ ਨਾਂਮ",
    gender: "ਸੈਕਸ",
    age: "ਇੱਕ ਸਾਲ ਪੁਰਾਣਾ",
    nationality: "ਕੌਮੀਅਤ",
    phone: "ਫ਼ੋਨ",
    email: "ਈਮੇਲ",
    patientId: "ਪੀਆਈਡੀ ਮਰੀਜ਼ ਨੰਬਰ",
    sid: "SID ਕੋਡ",
    province: "ਸੂਬਾ/ਸ਼ਹਿਰ",
    district: "ਵਾਰਡ/ਕਮਿਊਨ",
    address: "ਪਤਾ",
    clinical: "ਕਲੀਨਿਕਲ",
    department: "ਸਬਸਿਸਟਮ",
    division: "ਵਿਸ਼ੇਸ਼ਤਾ",
    codeForm: "ਨਮੂਨਾ ਪਛਾਣ ਨੰਬਰ",
    bodyPart: "ਭਾਗ",
    resultTemplate: "ਨਤੀਜਿਆਂ ਦੀ ਨਮੂਨਾ ਪੜ੍ਹਨਾ",
    resultPrint: "ਨਤੀਜਾ ਫਾਰਮ ਪ੍ਰਿੰਟ ਕਰੋ",
    language: "ਭਾਸ਼ਾ",
    formName: "ਮਾਡਲ ਦਾ ਨਾਮ",
    formResult: "ਨਮੂਨੇ ਦਾ ਸਿੱਟਾ",
    createdAt: "ਲਾਗੂ ਕਰਨ ਦੀ ਮਿਤੀ",
    createdUser: "ਪ੍ਰਦਰਸ਼ਨ ਕਰਨ ਵਾਲਾ",
    technicalProtocol: "ਤਕਨੀਕੀ ਪ੍ਰਕਿਰਿਆ",
    imagingFindings: "ਚਿੱਤਰ ਵਰਣਨ",
    impression: "ਸਿੱਟਾ, ਨਿਦਾਨ",
    icd10Classification: "ICD-10 ਵਰਗੀਕਰਨ",
    gradingClassification: "ਗਰੇਡਿੰਗ, ਵਰਗੀਕਰਨ",
    differentialDiagnosis: "ਵਿਭਿੰਨ ਨਿਦਾਨ",
    recommendationsCounseling: "ਸਿਫ਼ਾਰਸ਼ਾਂ ਅਤੇ ਸਲਾਹ",
    illustrativeImages: "ਦ੍ਰਿਸ਼ਟਾਂਤ",
    doctor: "ਪ੍ਰਦਰਸ਼ਨਕਾਰੀ ਡਾਕਟਰ",
    time: "ਸਮਾਂ",
    Result_Report: "ਨਤੀਜਾ ਸ਼ੀਟ",
  },
  th: {
    administrativeInfo: "ข้อมูลการบริหาร",
    fullName: "ชื่อ-นามสกุล",
    gender: "เพศ",
    age: "อายุปี",
    nationality: "สัญชาติ",
    phone: "โทรศัพท์",
    email: "อีเมล",
    patientId: "หมายเลขผู้ป่วย PID",
    sid: "รหัส SID",
    province: "จังหวัด/เมือง",
    district: "เขต/ตำบล",
    address: "ที่อยู่",
    clinical: "ทางคลินิก",
    department: "ระบบย่อย",
    division: "ความเชี่ยวชาญ",
    codeForm: "ตัวอย่างหมายเลขประจำตัว",
    bodyPart: "ส่วนหนึ่ง",
    resultTemplate: "ตัวอย่างการอ่านผล",
    resultPrint: "แบบฟอร์มพิมพ์ผลลัพธ์",
    language: "ภาษา",
    formName: "ชื่อรุ่น",
    formResult: "บทสรุปของตัวอย่าง",
    createdAt: "วันที่เริ่มใช้งาน",
    createdUser: "ผู้แสดง",
    technicalProtocol: "กระบวนการทางเทคนิค",
    imagingFindings: "คำอธิบายภาพ",
    impression: "บทสรุป การวินิจฉัย",
    icd10Classification: "การจำแนกประเภท ICD-10",
    gradingClassification: "การให้เกรด การจำแนกประเภท",
    differentialDiagnosis: "การวินิจฉัยแยกโรค",
    recommendationsCounseling: "คำแนะนำและคำแนะนำ",
    illustrativeImages: "ภาพประกอบ",
    doctor: "แพทย์ผู้ทำการแสดง",
    time: "เวลา",
    Result_Report: "ใบผลการสอบ",
  },
  id: {
    administrativeInfo: "INFORMASI ADMINISTRATIF",
    fullName: "Nama lengkap",
    gender: "Seks",
    age: "Berusia tahun",
    nationality: "Kebangsaan",
    phone: "Telepon",
    email: "E-mail",
    patientId: "Nomor pasien PID",
    sid: "Kode SID",
    province: "Provinsi/Kota",
    district: "Lingkungan/Komune",
    address: "Alamat",
    clinical: "Klinis",
    department: "Subsistem",
    division: "Spesialisasi",
    codeForm: "Contoh nomor identifikasi",
    bodyPart: "Bagian",
    resultTemplate: "Contoh pembacaan hasil",
    resultPrint: "Cetak formulir hasil",
    language: "Bahasa",
    formName: "Nama model",
    formResult: "Kesimpulan dari sampel",
    createdAt: "Tanggal pelaksanaan",
    createdUser: "Penampil",
    technicalProtocol: "PROSES TEKNIS",
    imagingFindings: "DESKRIPSI GAMBAR",
    impression: "KESIMPULAN, DIAGNOSIS",
    icd10Classification: "Klasifikasi ICD-10",
    gradingClassification: "Pemeringkatan, klasifikasi",
    differentialDiagnosis: "Diagnosis banding",
    recommendationsCounseling: "REKOMENDASI ​​& SARAN",
    illustrativeImages: "ILUSTRASI",
    doctor: "DOKTER YANG MELAKUKAN",
    time: "Waktu",
    Result_Report: "Lembar hasil",
  },
  ms: {
    administrativeInfo: "MAKLUMAT PENTADBIRAN",
    fullName: "Nama penuh",
    gender: "Seks",
    age: "Berumur tahun",
    nationality: "kewarganegaraan",
    phone: "telefon",
    email: "E-mel",
    patientId: "nombor pesakit PID",
    sid: "Kod SID",
    province: "Wilayah/Bandar",
    district: "Wad/Komuniti",
    address: "Alamat",
    clinical: "klinikal",
    department: "Subsistem",
    division: "keistimewaan",
    codeForm: "Nombor pengenalan sampel",
    bodyPart: "Bahagian",
    resultTemplate: "Contoh bacaan keputusan",
    resultPrint: "Cetak borang keputusan",
    language: "Bahasa",
    formName: "Nama model",
    formResult: "Kesimpulan sampel",
    createdAt: "Tarikh pelaksanaan",
    createdUser: "Pelaku",
    technicalProtocol: "PROSES TEKNIKAL",
    imagingFindings: "PENERANGAN IMEJ",
    impression: "KESIMPULAN, DIAGNOSIS",
    icd10Classification: "Klasifikasi ICD-10",
    gradingClassification: "Penggredan, pengelasan",
    differentialDiagnosis: "Diagnosis pembezaan",
    recommendationsCounseling: "CADANGAN & NASIHAT",
    illustrativeImages: "MISALAN",
    doctor: "DOKTOR PERSEMBAHAN",
    time: "Masa",
    Result_Report: "Lembaran keputusan",
  },
  km: {
    administrativeInfo: "ព័ត៌មានរដ្ឋបាល",
    fullName: "ឈ្មោះពេញ",
    gender: "ការរួមភេទ",
    age: "មានអាយុមួយឆ្នាំ",
    nationality: "សញ្ជាតិ",
    phone: "ទូរស័ព្ទ",
    email: "អ៊ីមែល",
    patientId: "លេខអ្នកជំងឺ PID",
    sid: "លេខកូដ SID",
    province: "ខេត្ត/ក្រុង",
    district: "វួដ/ឃុំ",
    address: "អាស័យដ្ឋាន",
    clinical: "គ្លីនិក",
    department: "ប្រព័ន្ធរង",
    division: "ឯកទេស",
    codeForm: "លេខអត្តសញ្ញាណគំរូ",
    bodyPart: "ផ្នែក",
    resultTemplate: "ការអានលទ្ធផលគំរូ",
    resultPrint: "បោះពុម្ពទម្រង់លទ្ធផល",
    language: "ភាសា",
    formName: "ឈ្មោះម៉ូដែល",
    formResult: "ការសន្និដ្ឋាននៃគំរូ",
    createdAt: "កាលបរិច្ឆេទនៃការអនុវត្ត",
    createdUser: "អ្នកសំដែង",
    technicalProtocol: "ដំណើរការបច្ចេកទេស",
    imagingFindings: "ការពិពណ៌នារូបភាព",
    impression: "សេចក្តីសន្និដ្ឋាន ការធ្វើរោគវិនិច្ឆ័យ",
    icd10Classification: "ចំណាត់ថ្នាក់ ICD-10",
    gradingClassification: "ចំណាត់ថ្នាក់, ចំណាត់ថ្នាក់",
    differentialDiagnosis: "ការធ្វើរោគវិនិច្ឆ័យឌីផេរ៉ង់ស្យែល",
    recommendationsCounseling: "អនុសាសន៍ & ដំបូន្មាន",
    illustrativeImages: "រូបភាព",
    doctor: "វេជ្ជបណ្ឌិតអនុវត្ត",
    time: "ពេលវេលា",
    Result_Report: "សន្លឹកលទ្ធផល",
  },
  lo: {
    administrativeInfo: "ຂໍ້ມູນບໍລິຫານ",
    fullName: "ຊື່ເຕັມ",
    gender: "ເພດ",
    age: "ປີອາຍຸ",
    nationality: "ສັນຊາດ",
    phone: "ໂທລະສັບ",
    email: "ອີເມວ",
    patientId: "ໝາຍເລກຄົນເຈັບ PID",
    sid: "ລະຫັດ SID",
    province: "ແຂວງ/ເມືອງ",
    district: "ຫວອດ/ຊຸມຊົນ",
    address: "ທີ່ຢູ່",
    clinical: "ຄລີນິກ",
    department: "ລະບົບຍ່ອຍ",
    division: "ພິເສດ",
    codeForm: "ໝາຍເລກປະຈຳຕົວຕົວຢ່າງ",
    bodyPart: "ສ່ວນ",
    resultTemplate: "ຕົວຢ່າງການອ່ານຜົນໄດ້ຮັບ",
    resultPrint: "ພິມແບບຟອມຜົນໄດ້ຮັບ",
    language: "ພາສາ",
    formName: "ຊື່ຕົວແບບ",
    formResult: "ບົດສະຫຼຸບຂອງຕົວຢ່າງ",
    createdAt: "ວັນທີຂອງການປະຕິບັດ",
    createdUser: "ນັກສະແດງ",
    technicalProtocol: "ຂະບວນການທາງວິຊາການ",
    imagingFindings: "ລາຍລະອຽດຮູບພາບ",
    impression: "ສະຫຼຸບ, ການວິນິດໄສ",
    icd10Classification: "ການຈັດປະເພດ ICD-10",
    gradingClassification: "ການ​ຈັດ​ອັນ​ດັບ​, ການ​ຈັດ​ປະ​ເພດ​",
    differentialDiagnosis: "ການວິນິດໄສທີ່ແຕກຕ່າງກັນ",
    recommendationsCounseling: "ຄໍາແນະນໍາ & ຄໍາແນະນໍາ",
    illustrativeImages: "ຮູບແຕ້ມ",
    doctor: "ແພດປະຕິບັດ",
    time: "ເວລາ",
    Result_Report: "ໃບຜົນ",
  },
  my: {
    administrativeInfo: "စီမံခန့်ခွဲရေးအချက်အလက်",
    fullName: "နာမည်အပြည့်အစုံ",
    gender: "လိင်",
    age: "အသက် ... နှစ်",
    nationality: "လူမျိုးစု",
    phone: "ဖုန်း",
    email: "အီးမေးလ်",
    patientId: "PID လူနာနံပါတ်",
    sid: "ပြောထားပါတယ်။",
    province: "ပြည်နယ်/မြို့",
    district: "ရပ်ကွက်/ရပ်ကွက်",
    address: "လိပ်စာ",
    clinical: "လက်တွေ့",
    department: "စနစ်ခွဲ",
    division: "အထူးပြု",
    codeForm: "နမူနာ မှတ်ပုံတင်နံပါတ်",
    bodyPart: "အပိုင်း",
    resultTemplate: "ရလဒ်များကို နမူနာဖတ်ခြင်း။",
    resultPrint: "ရလဒ်ပုံစံကို ပုံနှိပ်ပါ။",
    language: "ဘာသာစကား",
    formName: "မော်ဒယ်အမည်",
    formResult: "နမူနာ၏နိဂုံး",
    createdAt: "အကောင်အထည်ဖော်သည့်ရက်စွဲ",
    createdUser: "ဖျော်ဖြေသူ",
    technicalProtocol: "နည်းပညာဆိုင်ရာလုပ်ငန်းစဉ်",
    imagingFindings: "ပုံဖော်ပြချက်",
    impression: "နိဂုံးချုပ်၊ ရောဂါရှာဖွေခြင်း။",
    icd10Classification: "ICD-10 အမျိုးအစားခွဲခြားခြင်း။",
    gradingClassification: "အဆင့်၊ အမျိုးအစားခွဲခြင်း။",
    differentialDiagnosis: "ကွဲပြားသောရောဂါလက္ခဏာ",
    recommendationsCounseling: "အကြံပြုချက်များနှင့် အကြံပြုချက်များ",
    illustrativeImages: "ပုံဥပမာ",
    doctor: "ဆောင်ရွက်ပေးနေသော ဆရာဝန်",
    time: "အချိန်",
    Result_Report: "ရလဒ်စာရွက်",
  },
  fil: {
    administrativeInfo: "IMPORMASYON NA PANGANGASIWA",
    fullName: "Buong pangalan",
    gender: "kasarian",
    age: "Taon gulang",
    nationality: "Nasyonalidad",
    phone: "Telepono",
    email: "Email",
    patientId: "Numero ng pasyente ng PID",
    sid: "SID Code",
    province: "Lalawigan/Lungsod",
    district: "Ward/Commune",
    address: "Address",
    clinical: "Klinikal",
    department: "Subsystem",
    division: "Espesyalidad",
    codeForm: "Halimbawang numero ng pagkakakilanlan",
    bodyPart: "Bahagi",
    resultTemplate: "Halimbawang pagbabasa ng mga resulta",
    resultPrint: "I-print ang form ng mga resulta",
    language: "Wika",
    formName: "Pangalan ng modelo",
    formResult: "Konklusyon ng sample",
    createdAt: "Petsa ng pagpapatupad",
    createdUser: "Ang performer",
    technicalProtocol: "TEKNIKAL NA PROSESO",
    imagingFindings: "PAGLALARAWAN NG LARAWAN",
    impression: "KONKLUSYON, DIAGNOSIS",
    icd10Classification: "Pag-uuri ng ICD-10",
    gradingClassification: "Pagmamarka, pag-uuri",
    differentialDiagnosis: "Differential diagnosis",
    recommendationsCounseling: "MGA REKOMENDASYON AT PAYO",
    illustrativeImages: "ILUSTRASYON",
    doctor: "NAGMAMAYANG DOKTOR",
    time: "Oras",
    Result_Report: "sheet ng resulta",
  },
  sw: {
    administrativeInfo: "TAARIFA ZA UTAWALA",
    fullName: "Jina kamili",
    gender: "Ngono",
    age: "Umri wa miaka",
    nationality: "Utaifa",
    phone: "Simu",
    email: "Barua pepe",
    patientId: "Nambari ya mgonjwa wa PID",
    sid: "Msimbo wa SID",
    province: "Mkoa/Jiji",
    district: "Kata/Wilaya",
    address: "Anwani",
    clinical: "Kliniki",
    department: "Mfumo mdogo",
    division: "Umaalumu",
    codeForm: "Nambari ya kitambulisho ya mfano",
    bodyPart: "Sehemu",
    resultTemplate: "Usomaji wa mfano wa matokeo",
    resultPrint: "Chapisha fomu ya matokeo",
    language: "Lugha",
    formName: "Jina la mfano",
    formResult: "Hitimisho la sampuli",
    createdAt: "Tarehe ya utekelezaji",
    createdUser: "Muigizaji",
    technicalProtocol: "MCHAKATO WA KIUFUNDI",
    imagingFindings: "MAELEZO YA PICHA",
    impression: "HITIMISHO, UTAMBUZI",
    icd10Classification: "Uainishaji wa ICD-10",
    gradingClassification: "Uainishaji, uainishaji",
    differentialDiagnosis: "Utambuzi tofauti",
    recommendationsCounseling: "MAPENDEKEZO NA USHAURI",
    illustrativeImages: "MFANO",
    doctor: "DAKTARI WA UTENDAJI",
    time: "Muda",
    Result_Report: "Karatasi ya matokeo",
  },
  am: {
    administrativeInfo: "የአስተዳደር መረጃ",
    fullName: "ሙሉ ስም",
    gender: "ወሲብ",
    age: "አመት",
    nationality: "ዜግነት",
    phone: "ስልክ",
    email: "ኢሜይል",
    patientId: "የ PID ታካሚ ቁጥር",
    sid: "SID ኮድ",
    province: "አውራጃ/ከተማ",
    district: "ዋርድ/ኮምዩን",
    address: "አድራሻ",
    clinical: "ክሊኒካዊ",
    department: "ንዑስ ስርዓት",
    division: "ልዩ",
    codeForm: "የናሙና መለያ ቁጥር",
    bodyPart: "ክፍል",
    resultTemplate: "የውጤቶች ናሙና ንባብ",
    resultPrint: "የውጤት ቅጽ አትም",
    language: "ቋንቋ",
    formName: "የሞዴል ስም",
    formResult: "የናሙና መደምደሚያ",
    createdAt: "የተተገበረበት ቀን",
    createdUser: "ፈጻሚው",
    technicalProtocol: "ቴክኒካል ሂደት",
    imagingFindings: "የምስል መግለጫ",
    impression: "ማጠቃለያ, ምርመራ",
    icd10Classification: "ICD-10 ምደባ",
    gradingClassification: "ደረጃ አሰጣጥ, ምደባ",
    differentialDiagnosis: "ልዩነት ምርመራ",
    recommendationsCounseling: "ምክሮች እና ምክሮች",
    illustrativeImages: "ILUSTRATION",
    doctor: "በማከናወን ላይ ሐኪም",
    time: "ጊዜ",
    Result_Report: "የውጤት ሉህ",
  },
  af: {
    administrativeInfo: "ADMINISTRATIEWE INLIGTING",
    fullName: "Volle naam",
    gender: "Seks",
    age: "Jaar oud",
    nationality: "Nasionaliteit",
    phone: "Foon",
    email: "E-pos",
    patientId: "PID-pasiëntnommer",
    sid: "SID-kode",
    province: "Provinsie/Stad",
    district: "Wyk/Gemeente",
    address: "Adres",
    clinical: "Kliniese",
    department: "Substelsel",
    division: "Spesialiteit",
    codeForm: "Voorbeeldidentifikasienommer",
    bodyPart: "Deel",
    resultTemplate: "Voorbeeldlesing van resultate",
    resultPrint: "Druk resultatevorm af",
    language: "Taal",
    formName: "Modelnaam",
    formResult: "Gevolgtrekking van die monster",
    createdAt: "Datum van implementering",
    createdUser: "Die uitvoerder",
    technicalProtocol: "TEGNIESE PROSES",
    imagingFindings: "BEELDBESKRYWING",
    impression: "GEVOLGTREKKING, DIAGNOSE",
    icd10Classification: "ICD-10 Klassifikasie",
    gradingClassification: "Gradering, klassifikasie",
    differentialDiagnosis: "Differensiële diagnose",
    recommendationsCounseling: "AANBEVELINGS EN ADVIES",
    illustrativeImages: "ILLUSTRASIE",
    doctor: "UITVOERENDE DOKTER",
    time: "Tyd",
    Result_Report: "Resultateblad",
  },
  yo: {
    administrativeInfo: "ALAYE Isakoso",
    fullName: "Akokun Oruko",
    gender: "Ibalopo",
    age: "Odun kan",
    nationality: "Orilẹ-ede",
    phone: "Foonu",
    email: "Imeeli",
    patientId: "Nọmba alaisan PID",
    sid: "SID koodu",
    province: "Agbegbe / Ilu",
    district: "Ward / Agbegbe",
    address: "Adirẹsi",
    clinical: "Isẹgun",
    department: "Subsystem",
    division: "Pataki",
    codeForm: "Nọmba idanimọ apẹẹrẹ",
    bodyPart: "Apakan",
    resultTemplate: "Ayẹwo kika ti awọn esi",
    resultPrint: "Sita esi fọọmu",
    language: "Ede",
    formName: "Orukọ awoṣe",
    formResult: "Ipari ti awọn ayẹwo",
    createdAt: "Ọjọ imuse",
    createdUser: "Elere",
    technicalProtocol: "Ilana imọ ẹrọ",
    imagingFindings: "Apejuwe aworan",
    impression: "Ipari, OWO",
    icd10Classification: "ICD-10 Iyasọtọ",
    gradingClassification: "Idiwon, classification",
    differentialDiagnosis: "Ayẹwo iyatọ",
    recommendationsCounseling: "Awọn iṣeduro & Imọran",
    illustrativeImages: "Àpèjúwe",
    doctor: "ONISEGUN",
    time: "Akoko",
    Result_Report: "Iwe abajade",
  },
  ig: {
    administrativeInfo: "Ozi nchịkwa",
    fullName: "Aha n'uju",
    gender: "Mmekọahụ",
    age: "Otu afọ",
    nationality: "Obodo",
    phone: "Ekwentị",
    email: "Email",
    patientId: "Nọmba onye ọrịa PID",
    sid: "Koodu SID",
    province: "Mpaghara/Obodo",
    district: "Ward/Ogbako",
    address: "Adreesị",
    clinical: "Clinical",
    department: "Sistemụ sub",
    division: "Ọpụrụiche",
    codeForm: "Nọmba njirimara sample",
    bodyPart: "Akụkụ",
    resultTemplate: "Ọgụgụ ihe nlele nke nsonaazụ",
    resultPrint: "Bipụta ụdị nsonaazụ",
    language: "Asụsụ",
    formName: "Aha nlereanya",
    formResult: "Mmechi nke sample",
    createdAt: "Ụbọchị mmejuputa iwu",
    createdUser: "Onye na-eme ihe nkiri",
    technicalProtocol: "Usoro nka nka",
    imagingFindings: "Nkọwa onyonyo",
    impression: "NKWUBIOKWU, Nchọpụta",
    icd10Classification: "Nhazi ICD-10",
    gradingClassification: "Nhazi, nhazi ọkwa",
    differentialDiagnosis: "Nchọpụta dị iche iche",
    recommendationsCounseling: "NDỤMỌDỤ & NDỤMỌDỤ",
    illustrativeImages: "Ntụle",
    doctor: "Dọkịta na-eme",
    time: "Oge",
    Result_Report: "Mpempe akwụkwọ nsonaazụ",
  },
  ha: {
    administrativeInfo: "BAYANIN MULKI",
    fullName: "Cikakken suna",
    gender: "Jima'i",
    age: "Shekara daya",
    nationality: "Dan kasa",
    phone: "Waya",
    email: "Imel",
    patientId: "Lambar mara lafiya PID",
    sid: "Lambar SID",
    province: "Lardi / Birni",
    district: "Ward/Communication",
    address: "Adireshi",
    clinical: "Na asibiti",
    department: "Subsystem",
    division: "Kwarewa",
    codeForm: "Samfurin ganewa lambar",
    bodyPart: "Sashe",
    resultTemplate: "Misalin karatun sakamako",
    resultPrint: "Buga sigar sakamako",
    language: "Harshe",
    formName: "Sunan samfurin",
    formResult: "Ƙarshen samfurin",
    createdAt: "Ranar aiwatarwa",
    createdUser: "Mai yin wasan kwaikwayo",
    technicalProtocol: "TSARIN FASAHA",
    imagingFindings: "BAYANIN HOTO",
    impression: "KAMMALAWA, GANE",
    icd10Classification: "Saukewa: ICD-10",
    gradingClassification: "Grading, rarrabuwa",
    differentialDiagnosis: "ganewar asali daban-daban",
    recommendationsCounseling: "NASARA & NASIHA",
    illustrativeImages: "MISALI",
    doctor: "LIKITA MAI YI",
    time: "Lokaci",
    Result_Report: "Takardar sakamako",
  },
  is: {
    administrativeInfo: "STJÓRNVÖRUUPPLÝSINGAR",
    fullName: "Fullt nafn",
    gender: "Kynlíf",
    age: "Árs gamalt",
    nationality: "Þjóðerni",
    phone: "Sími",
    email: "Tölvupóstur",
    patientId: "PID sjúklinganúmer",
    sid: "SID kóði",
    province: "Sýsla/borg",
    district: "Kjördæmi/Sveitarfélag",
    address: "Heimilisfang",
    clinical: "Klínískt",
    department: "Undirkerfi",
    division: "Sérgrein",
    codeForm: "Auðkennisnúmer sýnishorns",
    bodyPart: "Hluti",
    resultTemplate: "Dæmi um lestur niðurstaðna",
    resultPrint: "Prenta niðurstöðueyðublað",
    language: "Tungumál",
    formName: "Nafn líkans",
    formResult: "Niðurstaða úrtaksins",
    createdAt: "Dagsetning framkvæmdar",
    createdUser: "Flytjandinn",
    technicalProtocol: "TÆKNILEGT FERLI",
    imagingFindings: "MYND LÝSING",
    impression: "NIÐURSTAÐA, GREINING",
    icd10Classification: "ICD-10 flokkun",
    gradingClassification: "Einkunn, flokkun",
    differentialDiagnosis: "Mismunagreining",
    recommendationsCounseling: "TILLÖGUR OG RÁÐGJÖF",
    illustrativeImages: "MYNDSKEIÐ",
    doctor: "LÆKNIR Í STARFSEMI",
    time: "Tími",
    Result_Report: "Niðurstöðublað",
  },
  ga: {
    administrativeInfo: "FAISNÉIS RIARACHÁIN",
    fullName: "Ainm iomlán",
    gender: "Gnéas",
    age: "Bliain d'aois",
    nationality: "Náisiúntacht",
    phone: "Fón",
    email: "Ríomhphost",
    patientId: "Uimhir othair PID",
    sid: "Cód SID",
    province: "Cúige/Cathair",
    district: "Barda/Común",
    address: "Seoladh",
    clinical: "Cliniciúil",
    department: "Fochóras",
    division: "Speisialtacht",
    codeForm: "Uimhir aitheantais shamplach",
    bodyPart: "Cuid",
    resultTemplate: "Léamh samplach ar thorthaí",
    resultPrint: "Foirm torthaí a phriontáil",
    language: "Teanga",
    formName: "Ainm an mhúnla",
    formResult: "Conclúid an tsampla",
    createdAt: "Dáta cur i bhfeidhm",
    createdUser: "An taibheoir",
    technicalProtocol: "PRÓISEAS TEICNIÚIL",
    imagingFindings: "CUR SÍOS AR AN ÍOMHÁ",
    impression: "CONCLÚID, DIAGNÓIS",
    icd10Classification: "Aicmiú ICD-10",
    gradingClassification: "Grádú, aicmiú",
    differentialDiagnosis: "Diagnóis dhifreálach",
    recommendationsCounseling: "MOLTAÍ & COMHAIRLE",
    illustrativeImages: "LÉARÚ",
    doctor: "DOCHTÚIR FEIRMIÚCHÁIN",
    time: "Am",
    Result_Report: "Bileog torthaí",
  },
  mt: {
    administrativeInfo: "INFORMAZZJONI AMMINISTRATTIVA",
    fullName: "Isem sħiħ",
    gender: "Sess",
    age: "Sena",
    nationality: "Nazzjonalità",
    phone: "Telefon",
    email: "Email",
    patientId: "Numru tal-pazjent PID",
    sid: "Kodiċi SID",
    province: "Provinċja/Belt",
    district: "Ward/Komun",
    address: "Indirizz",
    clinical: "Kliniku",
    department: "Sottosistema",
    division: "Speċjalità",
    codeForm: "Numru ta' identifikazzjoni tal-kampjun",
    bodyPart: "Parti",
    resultTemplate: "Qari ta' kampjuni tar-riżultati",
    resultPrint: "Formola tar-riżultati tal-istampar",
    language: "Lingwa",
    formName: "Isem tal-mudell",
    formResult: "Konklużjoni tal-kampjun",
    createdAt: "Data tal-implimentazzjoni",
    createdUser: "L-artist",
    technicalProtocol: "PROĊESS TEKNIKU",
    imagingFindings: "DESKRIZZJONI TAL-IMMAĠNI",
    impression: "KONKLUŻJONI, DIJANJOŻI",
    icd10Classification: "Klassifikazzjoni tal-ICD-10",
    gradingClassification: "Gradazzjoni, klassifikazzjoni",
    differentialDiagnosis: "Dijanjosi differenzjali",
    recommendationsCounseling: "RAKKOMANDAZZJONIJIET U PARIRI",
    illustrativeImages: "ILLUSTRAZZJONI",
    doctor: "TABIB LI JIPPERFORMA",
    time: "Ħin",
    Result_Report: "Folja tar-riżultati",
  },
  cy: {
    administrativeInfo: "GWYBODAETH WEINYDDOL",
    fullName: "Enw llawn",
    gender: "Rhyw",
    age: "Blwyddyn oed",
    nationality: "Cenedligrwydd",
    phone: "Ffôn",
    email: "E-bost",
    patientId: "Rhif claf PID",
    sid: "Cod SID",
    province: "Talaith/Dinas",
    district: "Ward/Cymuned",
    address: "Cyfeiriad",
    clinical: "Clinigol",
    department: "Is-system",
    division: "Arbenigedd",
    codeForm: "Rhif adnabod sampl",
    bodyPart: "Rhan",
    resultTemplate: "Darlleniad sampl o ganlyniadau",
    resultPrint: "Argraffu ffurflen canlyniadau",
    language: "Iaith",
    formName: "Enw'r model",
    formResult: "Casgliad y sampl",
    createdAt: "Dyddiad gweithredu",
    createdUser: "Y perfformiwr",
    technicalProtocol: "PROSES DECHNEGOL",
    imagingFindings: "DISGRIFIAD O'R DELWEDD",
    impression: "CASGLIAD, DIAGNOSIS",
    icd10Classification: "Dosbarthiad ICD-10",
    gradingClassification: "Graddio, dosbarthu",
    differentialDiagnosis: "Diagnosis gwahaniaethol",
    recommendationsCounseling: "ARGYMHELLION A CHYNGOR",
    illustrativeImages: "DARLUNIAD",
    doctor: "MEDDYG PERFFORMIO",
    time: "Amser",
    Result_Report: "Taflen ganlyniadau",
  },
};
